### PR TITLE
Code clean up around isUpToDateFastCheck 

### LINKED ISSUE #3896: Precondition fails on check for "public.databasechangeloglock" exists
### Search first

- [X] I searched and no similar issues were found

### Description

It appears that the latest version 4.19.1 may have introduced a regression with a precondition check failure. This occurs when the liquibase related tables have not been created on first changelog execution and there is a precondition that does a select count on the "databasechangeloglock" table:

```text
liquibase update --changelog-file changelog.yaml --url jdbc:postgresql://localhost:5432/postgres
####################################################
##   _     _             _ _                      ##
##  | |   (_)           (_) |                     ##
##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
##              | |                               ##
##              |_|                               ##
##                                                ##
##  Get documentation at docs.liquibase.com       ##
##  Get certified courses at learn.liquibase.com  ##
##  Free schema change activity reports at        ##
##      https://hub.liquibase.com                 ##
##                                                ##
####################################################
Starting Liquibase at 13:04:43 (version 4.19.1 #7641 built at 2023-02-28 18:08+0000)
Liquibase Version: 4.19.1
Liquibase Open Source 4.19.1 by Liquibase
Validation Error:
     1 preconditions generated an error
          changelog.yaml : liquibase.precondition.core.SqlPrecondition@1416cf9f : ERROR: relation "public.databasechangeloglock" does not exist
  Position: 22

Unexpected error running Liquibase: Validation Failed:
     1 preconditions generated an error
     changelog.yaml : liquibase.precondition.core.SqlPrecondition@1416cf9f : ERROR: relation "public.databasechangeloglock" does not exist
  Position: 22
```

The changelog file referenced works with the previous version 4.19.0.

### Steps To Reproduce

`liquibase update --changelog-file changelog.yaml --url jdbc:postgresql://localhost:5432/postgres`

changelog.yaml

```yaml
databaseChangeLog:
  - preConditions:
      - onFail: HALT
      - sqlCheck:
          expectedResult: 1
          sql: select count(*) from public.databasechangeloglock
  - changeSet:
      id: 1
      author: pscherer
      changes:
        - sql:
            endDelimiter: ;
            sql: CREATE SCHEMA test
```

### Actual Behavior

Precondition failure occurs and halts the execution of applying the changelog.

### Expected/Desired Behavior

Changelog file is applied successfully.

### Liquibase Version

4.19.1

### Database Vendor & Version

Postgresql 15.2_3

### Liquibase Integration

CLI

### Liquibase Extensions

_No response_

### OS and/or Infrastructure Type/Provider

MacOS 13.2.1

### Additional Context

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

### PR DESCRIPTION
**Pull request by MalloD12**
## Impact

- [ ] Bug fix (non-breaking change which fixes expected existing functionality)
- [x] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

Clean up done around `isUpToDateFastCheck()` method:

- Removed from Liquibase class
- As well as removed it's tests
- Added tests as part of UpdateCommandStep.

This is related, but not directly fix #3896. We will create a separate issue to investigate if there are required changes to perform regarding preconditions when using `isUpToDateFastCheck()` logic. 

## Things to be aware of

- None

## Things to worry about

- None

## Additional Context

- Nothing

### CODE REVIEW

File: liquibase-core/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java [hunk 1]
```diff
@@ -112,7 +112,7 @@ public void run(CommandResultsBuilder resultsBuilder) throws Exception {
             }
             throw e;
         } finally {
-            //TODO: We should be able to remove this once we get the rest of the update family
+            //gTODO: We should be able to remove this once we get the rest of the update family
```
Comment (filipelautert) [inline liquibase-core/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java:115]: this g seems "a" typo?

File: liquibase-core/src/main/java/liquibase/Liquibase.java [hunk 2]
```diff
@@ -260,6 +260,7 @@ public void update(Contexts contexts, LabelExpression labelExpression, boolean c
      * <p>
      * NOTE: to reduce the number of queries to the databasehistory table, this method will cache the "fast check" results within this instance under the assumption that the total changesets will not change within this instance.
      */
+    @Deprecated
     protected boolean isUpToDateFastCheck(Contexts contexts, LabelExpression labelExpression) throws LiquibaseException {
         String cacheKey = contexts +"/"+ labelExpression;
         if (!this.upToDateFastCheck.containsKey(cacheKey)) {
```
Comment (filipelautert) [inline liquibase-core/src/main/java/liquibase/Liquibase.java:266]: Can you remove this code and replace it with a call to UpdateCommandStep.isUpToDateFastCheck() ?

File: liquibase-core/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java (hunk 1 above)
Comment (MalloD12) [reply liquibase-core/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java:115]: Yeah, it was a typo. Fixing it.

File: liquibase-core/src/main/java/liquibase/Liquibase.java (hunk 2 above)
Comment (filipelautert) [reply liquibase-core/src/main/java/liquibase/Liquibase.java:267]: Sure, leave the method. But this method could call UpdateCommandStep.isUpToDateFastCheck() instead of duplicating the logic.

**Review by suryaaki2 — APPROVED** [review]

**Comment by XDelphiGrl** [comment]
Functional Tests Started Here: [https://github.com/liquibase/liquibase-pro-tests/actions/runs/4854383102](https://github.com/liquibase/liquibase-pro-tests/actions/runs/4854383102)

Test Harness Execution Started Here: [https://github.com/liquibase/liquibase-test-harness/actions/runs/4854378951](https://github.com/liquibase/liquibase-test-harness/actions/runs/4854378951)

File: liquibase-core/src/main/java/liquibase/Liquibase.java (hunk 2 above)
Comment (filipelautert) [reply liquibase-core/src/main/java/liquibase/Liquibase.java]: Yes, please :)

Comment (MalloD12) [reply liquibase-core/src/main/java/liquibase/Liquibase.java]: Done!

**Review by XDelphiGrl — APPROVED** [review]
This PR deprecates the `isUpToDateFastCheck` method in Liquibase.java. The method is now in the AbstractUpdateCommandStep class. If your code is using the deprecated version, consider updating to use the new method to prevent trouble when deprecated methods are removed.
* New command step unit tests added.
* Functional and test harness executions passing.
* No additional testing required.

APPROVED
