### PR TITLE
Make EnterpriseDBDatabase detection less broad

### LINKED ISSUE #2363: Liquibase chooses wrong Database implementation in version 4.7.0
## Environment

**Liquibase Version**: 4.7.0

**Liquibase Integration & Version**:  CLI

**Liquibase Extension(s) & Version**: -

**Database Vendor & Version**: Azure SQL Database v12.0.2000.8

**Operating System Type & Version**: Ubuntu 18.04

## Description
We recently started using Liquibase using the Docker image, we used the latest tag which resolved to Liquibase v4.7.0. 
We run the Liquibase container against multiple environments (Dev/Prod/etc) and some environments would consistently fail while others consistently succeeded. The commands were similar because we use a template, with only configuration (ip, username's) differing according to the environment.

It would fail with the error message saying:
` Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Invalid column name 'FALSE'. `

Even though the correct driver is being used (as shown in the logs below), Liquibase seems to be using PostgreSQL syntax. If googling for "pg_settings" it seems to be a PostgreSQL thing. Also, FALSE/TRUE seem to be PostgreSQL reserved keywords, that's why Liquibase is trying to use FALSE/TRUE without quotations, this doesn't work in MSSQL. 

## Steps To Reproduce
Run the Liquibase update command using version 4.7.0.
We didn't figure out why it would succeed on some environments and fail on others.

## Actual Behavior
Liquibase would fail even before applying our changesets, these errors would only be visible after using `--log-level=INFO`:
Log of Liquibase failing to find "pg_settings":
```
[2022-01-13 10:34:55] INFO [liquibase.database] Cannot check pg_settings
com.microsoft.sqlserver.jdbc.SQLServerException: Invalid object name 'pg_settings'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:872)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:767)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7375)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3200)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeQuery(SQLServerStatement.java:692)
	at liquibase.database.core.PostgresDatabase.setConnection(PostgresDatabase.java:176)
	at liquibase.database.DatabaseFactory.findCorrectDatabaseImplementation(DatabaseFactory.java:121)
	at liquibase.database.DatabaseFactory.openDatabase(DatabaseFactory.java:141)
	at liquibase.integration.commandline.CommandLineUtils.createDatabaseObject(CommandLineUtils.java:92)
	at liquibase.integration.commandline.Main.doMigration(Main.java:1517)
	at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:398)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
        at liquibase.integration.commandline.Main$1.run(Main.java:397)
	at liquibase.integration.commandline.Main$1.run(Main.java:221)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.integration.commandline.Main.run(Main.java:221)
	at liquibase.command.AbstractCliWrapperCommandStep.run(AbstractCliWrapperCommandStep.java:32)
	at liquibase.command.CommandScope.execute(CommandScope.java:157)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:45)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:15)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:325)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:291)
	at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:80)
```

Log of Liquibase failing to call a non-existent MSSQL function:
```
[2022-01-13 10:34:55] INFO [liquibase.database] Error getting default schema
liquibase.exception.DatabaseException: Error executing SQL select current_schema(): 'current_schema' is not a recognized built-in function name.
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:126)
	at liquibase.executor.jvm.JdbcExecutor.query(JdbcExecutor.java:161)
	at liquibase.command.CommandScope.execute(CommandScope.java:157)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:45)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:15)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:325)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:291)
	at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:80)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: 'current_schema' is not a recognized built-in function name.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:602)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:524)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7375)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3200)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:446)
	at liquibase.executor.jvm.JdbcExecutor$QueryCallableStatementCallback.doInCallableStatement(JdbcExecutor.java:498)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:119)
	... 36 more
```

And finally, Liquibase running a syntactical incorrect MSSQL statement:
```
Unexpected error running Liquibase: Error executing SQL UPDATE databasechangeloglock SET LOCKED = TRUE, LOCKEDBY = 'REDACTED (172.17.0.5)', LOCKGRANTED = '2022-01-13 10:34:56.274' WHERE ID = 1 AND LOCKED = FALSE: Invalid column name 'FALSE'.

liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: Error executing SQL UPDATE databasechangeloglock SET LOCKED = TRUE, LOCKEDBY = 'ecbcf27073d2 (172.17.0.5)', LOCKGRANTED = '2022-01-13 10:34:56.274' WHERE ID = 1 AND LOCKED = FALSE: Invalid column name 'FALSE'.
	at liquibase.command.CommandScope.execute(CommandScope.java:163)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:45)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:15)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:325)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:291)
	at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:80)
```

## Expected/Desired Behavior
As said before, some environments would succeed. Liquibase correctly executed the changesets. This is the kind of logging we would have expected on the failing environments:

```
Starting Liquibase at 10:33:58 (version 4.7.0 #1140 built at 2022-01-07 19:26+0000)
Liquibase Version: 4.7.0
Liquibase Community 4.7.0 by Liquibase
[2022-01-13 10:33:59] INFO [liquibase.database] Set default schema name to REDACTED
[2022-01-13 10:33:59] INFO [liquibase.lockservice] Successfully acquired change log lock
[2022-01-13 10:34:00] INFO [liquibase.changelog] Reading from DATABASECHANGELOG
[2022-01-13 10:34:00] INFO [liquibase.lockservice] Successfully released change log lock
[2022-01-13 10:34:00] INFO [liquibase.lockservice] Successfully acquired change log lock
Skipping auto-registration
[2022-01-13 10:34:00] WARNING [liquibase.hub] Skipping auto-registration
[2022-01-13 10:34:00] INFO [liquibase.lockservice] Successfully released change log lock
Liquibase command 'update' was executed successfully.
```

## Additional Context
We solved this issue by using Liquibase version v4.6.2 for now, this version gives us no problems and all of our changesets are executed succesfully. We changed the docker `latest` tag to `4.6.2`.

### PR DESCRIPTION
**Pull request by nvoxland**
## Description
The current implementation of EnterpriseDBDatabase picks up database with just "edb" in the url anywhere vs. an actual edb url.

Fixes #2363 

## Work Around
You can manually override the (wrongly) detected dialect with `databaseClass: liquibase.database.core.MySQLDatabase` or `databaseClass: liquibase.database.core.DB2Database` etc. in your liquibase.properties file.

- - -
#### Links
* Fixed Issue: [https://github.com/liquibase/liquibase/issues/2363](https://github.com/liquibase/liquibase/issues/2363)
* Test Results: [https://github.com/liquibase/liquibase/pull/2364/checks](https://github.com/liquibase/liquibase/pull/2364/checks)

#### Testing
* Steps to Reproduce: 
  * [https://github.com/liquibase/liquibase/issues/2363](https://github.com/liquibase/liquibase/issues/2363)
  * Connect to a non-postgresql url with "edb" in the url somewhere. Like jdb:mysql:localhost/testedb
* Guidance:
  * Impact: Fixes all databases, but change is only in edb code

#### Dev Verification
Added automated test to catch the problem

## Test Requirements (Liquibase Internal QA)
**Manual Tests**

**Setup: Case 1**

* Create a MySQL database named test*edb*1
* Update liquibase.properties file to connect to that database:
`url:jdbc:mysql://localhost:3309/testedb1?useSSL=false&allowPublicKeyRetrieval=true`
* Comment out or delete the `driver` name in liquibase.properties
* Comment out or delete the MySQL driver specified in the liquibase.properties `classpath.`
* Copy the MySQL driver into the liquibase/lib directory 

:warning: I found that if the driver was specified in the liquibase.properties file, you do not encounter this bug, even when a database URL contains the literal string `edb`. That is why the setup removes any reference to the driver class or driver jar. Liquibase does not ship with a MySQL jar in lib; we must add that manually to run this test. :warning:

##### Error Message output By Bug
```
[2022-01-19 12:26:29] INFO [liquibase.database] Cannot check pg_settings
java.sql.SQLSyntaxErrorException: Table 'testedb1.pg_settings' doesn't exist
```

**Verify non-Postgres/EDB JDBC URLs with “edb” do not try and use PG/EDB driver.**

* `liquibase log-level INFO update-sql --changelog-file <any changelog>`
* update-sql is successful
* there is no error about “pg_settings” in the output.

- - -
**Setup Case 2**

* Follow the instructions in [https://datical.atlassian.net/browse/LB-2185](https://datical.atlassian.net/browse/LB-2185|smart-link)  to start an EDB instance **on the default port (5444)**
* Create a database named ‘test’
* Update liquibase.properties to connect to the database:

` url:jdbc:edb://localhost:5444/test`

* Do not include driver name or driver jar in liquibase.properties file.
* Copy the edb jar into the liquibase/lib directory.
* Rename or delete the postgresql driver jar in liquibase/lib.

**Verify the EDB driver is used for a connection that has “edb” AND “:5444”**

* `liquibase log-level INFO update-sql --changelog-file <anychangelog>`
* update-sql is successful
* you do not get an error that the EDB driver cannot be located.

- - -
**Setup: Case 3**

* Start a second posgres  database on the default port (5432)
* Create a database named ‘test1’
* Update liquibase.properties to connect to the database:

`url: jdbc:postgresql://localhost:5432/test`

* Do not include driver name or driver jar in liquibase.properties file.
* Ensure the postgres driver is in liquibase/lib

**Verify the Postgres driver is used for a connection that has “postgres” and “:5432”**

* `liquibase log-level INFO update-sql --changelog-file <anychangelog>`
* update-sql is successful
* you do not get an error that the EDB driver cannot be located.
* the postgres driver is used.

- - -
**Automated Tests**

* None required for this ticket; there are nice unit tests for this change.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-2214) by [Unito](https://www.unito.io)

### CODE REVIEW

**Review by wwillard7800 — APPROVED** [review]

File: liquibase-core/src/main/java/liquibase/database/core/EnterpriseDBDatabase.java [hunk 1]
```diff
@@ -10,7 +10,7 @@
     @Override
     public boolean isCorrectDatabaseImplementation(DatabaseConnection conn) throws DatabaseException {
         final String url = conn.getURL();
-        return url.contains("edb") || (url.contains("postgres") && url.contains(":5444"));
+        return url.contains(":edb:") || (url.contains(":postgres:") && url.contains(":5444"));
```
Comment (StevenMassaro) [inline liquibase-core/src/main/java/liquibase/database/core/EnterpriseDBDatabase.java:13]: Couldn't the user change the port to something other than 5444? That appears to just be the default.

https://www.enterprisedb.com/edb-docs/d/edb-backup-and-recovery-tool/installation-getting-started/installation-upgrade-guide/2.4/EDB_Postgres_Backup_and_Recovery_Installation_and_Upgrade_Guide.1.15.html

Comment (nvoxland) [reply liquibase-core/src/main/java/liquibase/database/core/EnterpriseDBDatabase.java:13]: The problem it's trying to addess is that EDB users can connect via a jdb:postgres URL and even the connection metadata we get back doesn't let us know it's edb vs. postgresql. This acts as a way to still flag the connection as probably edb in that case. 

If they are using edb and using the jdbc:postgres url and put it on a non-default port, it will fall back to thinking it's postgresql and they'll have to be either OK with that or tell us with the databaseClass argument. I don't think there's any other way we can know the actual db type.

Comment (StevenMassaro) [reply liquibase-core/src/main/java/liquibase/database/core/EnterpriseDBDatabase.java:13]: Regardless of which path we choose, sounds like we'll have the possibility for false detections on either side. I don't have a suggestion on how to improve this, so I'm not holding up this PR.

**Review by StevenMassaro — APPROVED** [review]

**Review by suryaaki2 — APPROVED** [review]

File: liquibase-core/src/main/java/liquibase/database/core/EnterpriseDBDatabase.java [hunk 2]
```diff
@@ -1,16 +1,38 @@
...
+                    if (stmt != null) {
+                        try (ResultSet rs = stmt.executeQuery("select version()")) {
+                            if (rs.next()) {
+                                return ((String) JdbcUtil.getResultSetValue(rs, 1)).startsWith("EnterpriseDB");
+                            }
+                        }
+                    }
+                } catch (SQLException throwables) {
+                    return false;
+                }
```
Comment (StevenMassaro) [inline liquibase-core/src/main/java/liquibase/database/core/EnterpriseDBDatabase.java:31]: There may be value in logging this exception, perhaps at a warning level.

**Comment by nvoxland** [comment]
I updated the code to check the connection to know if it's an edb database vs. purely relying on the url.

I left the jdbc:edb and jdbc:postgres checks in there around it, though, for performance reasons.

File: liquibase-core/src/main/java/liquibase/database/core/EnterpriseDBDatabase.java [hunk 3]
```diff
@@ -1,16 +1,40 @@
...
+import java.sql.SQLException;
+import java.sql.Statement;
 
 public class EnterpriseDBDatabase extends PostgresDatabase {
 
     @Override
     public boolean isCorrectDatabaseImplementation(DatabaseConnection conn) throws DatabaseException {
         final String url = conn.getURL();
-        return url.contains("edb") || (url.contains("postgres") && url.contains(":5444"));
+        if (url.startsWith("jdbc:edb:") || url.startsWith("jdbc:postgres")) {
```
Comment (molivasdat) [inline liquibase-core/src/main/java/liquibase/database/core/EnterpriseDBDatabase.java:20]: Will this work with diffs and snapshots where the url potentially uses offline?  like the following **offline:<db_type>?snapshot**
In this case, it would be offline:edb?snapshot

Comment (nvoxland) [reply liquibase-core/src/main/java/liquibase/database/core/EnterpriseDBDatabase.java:20]: In those cases, the "offline:edb" part forces it to be edb so it doesn't need to use this method.
