### PR TITLE
Fix getting default schema issue for firebird

### LINKED ISSUE #2796: Change set always failed with `preConditions` contained `- foreignKeyConstraintExists` check
## Environment

**Liquibase Version**: 3.9.1 / 3.8.0 (tested for the both version)

**Database Vendor & Version**: mariaDB 2.7.4/ 3.4.0  (tested for the both version)

**Operating System Type & Version**: macOs Monterey ubuntu-18.04 / 12.0.1  (tested for the both version)

## Description
Hi team, 
We recently upgraded our project from version 4.1.0 to 4.9.1 to support changeSets fails logs. 
It's cool feature but in new version changeSets always failed with `preConditions` contained `- foreignKeyConstraintExists` check. Without this check, changeSets are ran successfully. However, this is a big problem for us, since there are quite a lot old changeSets in the system with this check. Now they failed. 

## Steps To Reproduce

List the steps to reproduce the behavior.
- Create database Table **Owner** = [id, name] and  **Dog** =  [id, name, ownerId] by changeSet 1
- Create index  **fk_Dog_Owner_id** for **ownerId** to Owner by changeSet 2
- Create foreignKey  **fk_Dog_Owner_id** for **ownerId** to Owner by changeSet 3
- Try drop foreignKey by changeSet  4 contained
```
      preConditions:
        - onFail: MARK_RAN
        - foreignKeyConstraintExists:
            indexName: fk_Dog_Owner_id
```
- ChangeSet failed

Also to reproduce problem you can clone project [https://github.com/KeyrisXdSnow/LiquibaseForeignKeyError](https://github.com/KeyrisXdSnow/LiquibaseForeignKeyError)

## Actual Behavior
Change set always failed with `preConditions` contained `- foreignKeyConstraintExists` check:
```
apr. 26, 2022 11:46:26 AM liquibase.changelog
INFO: Marking ChangeSet: 2.dropKey.yaml::dropIndex::keyris ran despite precondition failure due to onFail='MARK_RAN': 
          2.dropKey.yaml : Index fk_Dog_Owner_id does not exist
```

## Expected/Desired Behavior
 ChangeSet with tested with -` foreignKeyConstraintExists` check run successfully.
 
```
 Running Changeset: 2.dropKeyWithoutPreCondition.yaml::dropKeyWithoutPreCondition::keyris
apr. 26, 2022 11:48:01 AM liquibase.changelog
INFO: Foreign key fk_Dog_Owner_id dropped
apr. 26, 2022 11:48:01 AM liquibase.changelog
INFO: ChangeSet 2.dropKeyWithoutPreCondition.yaml::dropKeyWithoutPreCondition::keyris ran successfully in 205ms
Running Changeset: 2.dropKeyWithoutPreCondition.yaml::dropIndexWithoutPreCondition.yaml::keyris
apr. 26, 2022 11:48:01 AM liquibase.changelog
INFO: Index fk_Dog_Owner_id dropped from table Dog
apr. 26, 2022 11:48:01 AM liquibase.changelog
INFO: ChangeSet 2.dropKeyWithoutPreCondition.yaml::dropIndexWithoutPreCondition.yaml::keyris ran successfully in 248ms
apr. 26, 2022 11:48:01 AM liquibase.lockservice
INFO: Successfully released change log lock
apr. 26, 2022 11:48:01 AM liquibase.lockservice
INFO: Successfully released change log lock
```

### LINKED ISSUE #2874: firebird needs schema specification to run liquibase drop-all
Liquibase Version:
4.10.0

Liquibase Integration & Version: 
Core: //master/2708/0a9d6d/2022-05-23 15:17+0000, Pro: master/1291/728a05/2022-05-19T14:28:39Z

Database Vendor & Version:
Firebird jdbc: 3.0.6
Firebird docker conteiner: 4.0.1
Firebird api-connector 1.5

Operating System Type & Version:
Windows 10
Java 8

Description

`--schemas=*dbName*` is needed for running liquibase on a firebird database (its an odd behavior when it is not needed on other database types like mySQL)

Steps To Reproduce

1. Run a Firebird docker container
(Download firebird connector-api-1.5, its not included with liquibase)
2. Specify the user, pass, url and a changelog on your `liquibase.properties` or in the liquibase command 
3. Run `liquibase update`
4. Run `liquibase drop-all`

Actual Behavior
Liquibase cant run the command succesfully and it outputs the next error:
```
[2022-05-24 15:15:49] SEVERE [liquibase.integration] java.lang.NullPointerException
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: java.lang.NullPointerException
        at liquibase.command.CommandScope.execute(CommandScope.java:163)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:51)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:21)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:336)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:301)
        at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:90)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:91)
Caused by: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: java.lang.NullPointerException
        at liquibase.integration.commandline.Main$1.run(Main.java:443)
        at liquibase.integration.commandline.Main$1.run(Main.java:221)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.integration.commandline.Main.run(Main.java:221)
        at liquibase.command.AbstractCliWrapperCommandStep.run(AbstractCliWrapperCommandStep.java:32)
        at liquibase.command.CommandScope.execute(CommandScope.java:157)
        ... 20 more
Caused by: liquibase.exception.CommandExecutionException: liquibase.exception.DatabaseException: java.lang.NullPointerException
        at liquibase.command.CommandScope.execute(CommandScope.java:163)
        at liquibase.integration.commandline.Main.doMigration(Main.java:1825)
        at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:398)
        at liquibase.Scope.lambda$child$0(Scope.java:180)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:179)
        at liquibase.Scope.child(Scope.java:158)
        at liquibase.integration.commandline.Main$1.run(Main.java:397)
        ... 26 more
Caused by: liquibase.exception.DatabaseException: java.lang.NullPointerException
        at liquibase.command.core.InternalDropAllCommandStep.run(InternalDropAllCommandStep.java:115)
        at liquibase.command.CommandScope.execute(CommandScope.java:157)
        ... 33 more
Caused by: java.lang.NullPointerException
        at liquibase.command.core.InternalDropAllCommandStep.run(InternalDropAllCommandStep.java:97)
        ... 34 more


Unexpected error running Liquibase: java.lang.NullPointerException

liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: java.lang.NullPointerException
        at liquibase.command.CommandScope.execute(CommandScope.java:163)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:51)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:21)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:336)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:301)
        at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:90)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:91)
Caused by: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: java.lang.NullPointerException
        at liquibase.integration.commandline.Main$1.run(Main.java:443)
        at liquibase.integration.commandline.Main$1.run(Main.java:221)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.integration.commandline.Main.run(Main.java:221)
        at liquibase.command.AbstractCliWrapperCommandStep.run(AbstractCliWrapperCommandStep.java:32)
        at liquibase.command.CommandScope.execute(CommandScope.java:157)
        ... 20 more
Caused by: liquibase.exception.CommandExecutionException: liquibase.exception.DatabaseException: java.lang.NullPointerException
        at liquibase.command.CommandScope.execute(CommandScope.java:163)
        at liquibase.integration.commandline.Main.doMigration(Main.java:1825)
        at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:398)
        at liquibase.Scope.lambda$child$0(Scope.java:180)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:179)
        at liquibase.Scope.child(Scope.java:158)
        at liquibase.integration.commandline.Main$1.run(Main.java:397)
        ... 26 more
Caused by: liquibase.exception.DatabaseException: java.lang.NullPointerException
        at liquibase.command.core.InternalDropAllCommandStep.run(InternalDropAllCommandStep.java:115)
        at liquibase.command.CommandScope.execute(CommandScope.java:157)
        ... 33 more
Caused by: java.lang.NullPointerException
        at liquibase.command.core.InternalDropAllCommandStep.run(InternalDropAllCommandStep.java:97)
        ... 34 more

```

Expected/Desired Behavior
Liquibase runs `liquibase drop-all` succesfully 

Additional Context
Checked on a mySQL database and it doesnt have that behavior

### PR DESCRIPTION
**Pull request by MalloD12**
## Impact

- [x] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

Drop-all (as well as some other commands) were failing when trying to interact with the database objects as Firebird does not support schemas. To avoid this issue a fix for getting the default schema has been implemented. Also, support for executing Firebird integration tests has been implemented,  integration test data updated, and fix some issues found through integration test execution.

Fixes #2874

## Things to be aware of

- Implement `getConnectionCatalogName()` for Firebird as it doesn't support catalogs and schemas.
- Impact is only concentrate for Firebird database.

## Things to worry about

- List any questions or concerns you have with the change
- List unknowns you have 

## Additional Context

- Nothing

### CODE REVIEW

**Review by filipelautert — APPROVED** [review]
This PR reinstantiate (almost) all Firebird integration tests. 
We were unable to enable tests included from "common.tests.changelog.xml" file + other 4 tests overrided/ignored in FirebirdTestSystem . 
When this PR gets approved, we may open a new issue to reenable the remaining tests and it can be prioritized accordingly.

@MalloD12 I can't set you as reviewer, but as initial author of the change can you take a look at how it is now? Thanks

File: liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/core/FirebirdTestSystem.java [hunk 1]
```diff
@@ -15,9 +17,16 @@ public FirebirdTestSystem(Definition definition) {
         super(definition);
     }
 
+    @SuppressWarnings("java:S2095")
```
Comment (XDelphiGrl) [inline liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/core/FirebirdTestSystem.java:20]: @MalloD12, hello! Please add a comment as to why this Sonar warning is being suppressed. Thank you!

**Review by XDelphiGrl — APPROVED** [review]
Firebird does not support the `schema` object common to other relational DBs. Liquibase was incorrectly requiring Firebird users to supply a `--schemas=*dbName*` to execute the `drop-all` command; since schemas are not supported, Liquibase failed. This PR addresses this bug.
* New integration tests for Firebird added.
* Automated functional tests passing.
* Test harness execution failed due to an environmental issue in another database test suite; not applicable to this PR.
* No additional testing required.

NOTE: I did request that a comment be added to explain the suppression of a Sonar warning. I do not need to re-review this change just for that.

APPROVED

File: liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/core/FirebirdTestSystem.java (hunk 1 above)
Comment (MalloD12) [reply liquibase-extension-testing/src/main/java/liquibase/extension/testing/testsystem/core/FirebirdTestSystem.java]: @XDelphiGrl I think this piece of code was not up to date, because I can't see it anymore. Sorry for the confusion!

**Review by suryaaki2 — APPROVED** [review]
