### PR TITLE
Replace Statement by PreparedStament allowing the use of parameter markers on DB2z catalogue queries

### LINKED ISSUE #3791: Use parameter markers for catalogue queries
## Environment

**Liquibase Version**: 4.13

**Liquibase Integration & Version**: CLI,

**Database Vendor & Version**: DB2z 12

**Operating System Type & Version**: Windows 10 Pro

## Description

To retrieve catalog information, queries are used (especially for DB2z) that include the schema and table names as literals.

For example `

   SELECT 'NULL' AS TABLE_CAT,
   SYSTAB.TBCREATOR AS TABLE_SCHEM,
   SYSTAB.TBNAME AS TABLE_NAME, 
   COLUSE.COLNAME AS COLUMN_NAME,
   COLUSE.COLSEQ AS KEY_SEQ,
   SYSTAB.CONSTNAME AS PK_NAME
   FROM SYSIBM.SYSTABCONST SYSTAB
   JOIN SYSIBM.SYSKEYCOLUSE COLUSE
   ON SYSTAB.TBCREATOR = COLUSE.TBCREATOR
   HERE SYSTAB.TYPE = 'P'
   AND SYSTAB.TBNAME=**'DMTID3O'**
   AND SYSTAB.TBCREATOR=**'ENTW'**
   AND SYSTAB.TBNAME=COLUSE.TBNAME 
   AND SYSTAB.CONSTNAME=COLUSE.CONSTNAME
   ORDER BY COLUSE.COLNAME`

This floods the statement cache with similar queries and pushes out statements from other applications.
Also, statements need to be parsed and query plans need to be created unnecessarily.
Overall, the performance of Liquibase is reduced, but also that of the system as a whole.

It would be better to use queries with parameter markers.

## Steps To Reproduce

Use a ChangeLog with many preconditions, e.g. primaryKeyExists.

## Actual Behavior

Many, very similar queries are executed.

## Expected/Desired Behavior

One query with parameter markers is executed several times.

### PR DESCRIPTION
**Pull request by MichaelKern-IVV**
## Impact

- [ ] Bug fix (non-breaking change which fixes expected existing functionality)
- [x] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

Use parameter markers for DB2z catalogue queries to improve performance.

Fixes #3791 (partially)

### CODE REVIEW

**Comment by nvoxland** [comment]
**Initial/Pre-Review Thoughts**

Thanks for the fix, @MichaelKern-IVV ! Off hand the changes look to be in the right spot and make sense. We'll have a more complete code review soon.

Questions I have:
- None

Potential risks:
- None

What could make the full review difficult:
- Nothing

File: liquibase-core/src/main/java/liquibase/snapshot/ResultSetCache.java [hunk 1]
```diff
@@ -255,17 +255,29 @@ protected List<CachedRow> executeAndExtract(String sql, Database database) throw
...
+            return executeAndExtract(database, informixTrimHint, sql);
+        }
+
+        protected List<CachedRow> executeAndExtract(Database database, boolean informixTrimHint, String sql, Object...parameters)
+                throws DatabaseException, SQLException {
             if (sql == null) {
                 return new ArrayList<>();
             }
-            Statement statement = null;
+            PreparedStatement statement = null;
```
Comment (filipelautert) [inline liquibase-core/src/main/java/liquibase/snapshot/ResultSetCache.java:272]: This means that Liquibase will be using PreparedStatement instead of Statement for all queries that are executed (not only Db2) , even if we don't bind any parameters .
I compared functional tests with executions from other branches and seems it doesn't impact performance, but maybe it is something to keep in mind and this method is called in a lot of places.

**Review by filipelautert — APPROVED** [review]

**Comment by filipelautert** [comment]
Hello @MichaelKern-IVV - could you fix the merge conflicts? thanks!

**Comment by MichaelKern-IVV** [comment]
Accidentally closed and reopened

File: liquibase-core/src/main/java/liquibase/snapshot/ResultSetCache.java (hunk 1 above)
Comment (XDelphiGrl) [reply liquibase-core/src/main/java/liquibase/snapshot/ResultSetCache.java]: Do we need to wait for @nvoxland's response before we proceed with this PR, @filipelautert ?

**Review by XDelphiGrl — APPROVED** [review]
DB2z parameter markers improve performance by preparing the SQL statement once and reusing the associated query plan. This PR implements the ability to specify parameter markers in frequently executed DB2/Z queries via prepared statements.
* The test harness failures are environmental (Titan didn't start correctly for Firebird).
* Functional tests passed.
* No additional testing required.

[IBM Docs for Parameter Markers](https://www.ibm.com/docs/en/db2/11.5?topic=design-parameters-markers)

APPROVED
