### PR TITLE
Fixed #3971: "SAP SQL Anywhere 17.0.11: Liquibase incorrectly reports that TIMESTAMP requested precision is longer than TIMESTAMP supported precision"

### LINKED ISSUE #3971: SAP SQL Anywhere 17.0.11: Liquibase incorrectly reports that TIMESTAMP requested precision is longer than TIMESTAMP supported precision
### Search first

- [X] I searched and no similar issues were found

### Description

I am trying to `generateChangeLog` from a SAP SQL Anywhere 17.0.11 database which contains TIMESTAMP WITH TIME ZONE columns having a default of DEFAULT UTC TIMESTAMP.

Liquibase incorrectly complains that the supported precision is shorter than the requested precision:

```
liquibase.exception.LiquibaseException: liquibase.exception.CommandExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: liquibase.exception.DatabaseIncapableOfOperation: Using a TIMESTAMP data type with a fractional precision of 33 is not supported on asany: A timestamp datatype with 33 fractional digits was requested, but SQL Anywhere only supports 9 digits.
```

The message was true for older versions of SQL Anywhere which did not support "WITH TIME ZONE", but since current versions support "WITH TIME ZONE" this message is wrong now.

### Steps To Reproduce

`generateChangeLog` using SQL Anywhere 17.0.11 having a column with the definition `TIMESTAMP WITH TIMEZONE DEFAULT UTC TIMESTAMP`.

### Expected/Desired Behavior

Successfully accepts both, the type `TIMESTAMP WITH TIMEZONE` and the default value `UTC TIMESTAMP`.

### Liquibase Version

latest

### Database Vendor & Version

SAP SQL Anywhere 17.0.11

### Liquibase Integration

Maven Plugin

### Liquibase Extensions

none

### OS and/or Infrastructure Type/Provider

Windows 10

### Additional Context

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

### PR DESCRIPTION
**Pull request by mkarg**
Fixes #3971 

## Impact

- [x] Bug fix (non-breaking change which fixes expected existing functionality)
- [x] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

This PR tells Liquibase that SQL Anywhere is actually able to deal with the `WITH TIMEZONE` feature of the `TIMESTAMP` data type, and adds a test case to the existing integration test suite which proofs the functionality.

## Things to be aware of

N/A

## Things to worry about

N/A

## Additional Context

Developed using latest SQL Anywhere 17.0.11-7254 on Windows 10 Pro (German) as a standalone engine (hence not using Testcontainers), using latest official product documation from https://help.sap.com/docs/SAP_SQL_Anywhere/93079d4ba8e44920ae63ffb4def91f5b/81fe344c6ce21014a4f29d9e0af358b9.html?locale=en-US&q=TIMESTAMP%20WITH%20TIMEZONE.

### CODE REVIEW

**Comment by mkarg** [comment]
**Status:** Unfortunately the current changes are not good enough. Today's custom build (including *all* merged and open SQL Anywhere related PRs) still fails with the following message: `Unexpected error running Liquibase: liquibase.exception.DatabaseIncapableOfOperation: Using a TIMESTAMP data type with a fractional precision of 33 is not supported on asany: A timestamp datatype with 33 fractional digits was requested, but SQL Anywhere only supports 6 digits.`.

**Comment by mkarg** [comment]
@filipelautert Kindly requesting your review. I confirm this code correctly worked on SQL Anywhere 17.0.11, i. e. was able to generateChangeLog containing a TIMESTAMPT WITH TIMEZONE columne, while *without* this PR an error message is shown claiming that the RDBMS does not support 33 digits.

File: liquibase-standard/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java [hunk 1]
```diff
@@ -477,9 +477,9 @@ protected DataType readDataType(CachedRow columnMetadataResultSet, Column column
          */
         int jdbcType = columnMetadataResultSet.getInt("DATA_TYPE");
 
-        // Java 8 compatibility notes: When upgrading this project to JDK8 and beyond, also execute this if-branch
-        // if jdbcType is TIMESTAMP_WITH_TIMEZONE (does not exist yet in JDK7)
-        if (jdbcType == Types.TIMESTAMP) {
+        if (jdbcType == Types.TIMESTAMP || jdbcType == Types.TIMESTAMP_WITH_TIMEZONE
```
Comment (filipelautert) [inline liquibase-standard/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java:480]: This `|| jdbcType == Types.TIMESTAMP_WITH_TIMEZONE` wasn't here before.. is it required for asany too?

Comment (mkarg) [reply liquibase-standard/src/main/java/liquibase/snapshot/jvm/ColumnSnapshotGenerator.java:480]: Once SAP fixes the bug (i. e. reports a TIMESTAMP WITH TIMEZONE as a TIMESTAMP_WITH_TIMEZONE) then it will be necessary. Until then (i. e. as long as SAP reports a TIMESTAMP WITH TIMEZONE as a VARCHAR) it is not essentially needed to resolve *this* issue. But see, it was needed since long time, see the removed comment, so I thought we can fix both issues in one PR.

**Review by filipelautert — APPROVED** [review]
This PR fixes TIMESTAMP support for SQL Anywhere.

**Review by rberezen — APPROVED** [review]

**Comment by mkarg** [comment]
@filipelautert Why not merging this PR?
