### PR TITLE
#1066 addNotNullConstraint / dropNotNullConstraint not supported on Firebird

### LINKED ISSUE #1066: addNotNullConstraint / dropNotNullConstraint not supported on Firebird
**Description**
The change addNotNullConstraint and dropNotNullConstraint are not available for Firebird databases.

**To Reproduce**
Add the commands to a change set and run it against a Firebird database. As a result there will be the following error messages:
_addNotNullConstraint is not supported on firebird_
_dropNotNullConstraint is not supported on firebird_

**Expected behavior**
The commands should be available for Firebird databases as well.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-177) by [Unito](https://www.unito.io/learn-more)

### PR DESCRIPTION
**Pull request by Wallaby1999**
**Branch: Liquibase/master**

Content copied from issue #1066 

**Description**
The change addNotNullConstraint and dropNotNullConstraint are not available for Firebird databases.

**To Reproduce**
Add the commands to a change set and run it against a Firebird database. As a result there will be the following error messages:
addNotNullConstraint is not supported on firebird
dropNotNullConstraint is not supported on firebird

**Expected behavior**
The commands should be available for Firebird databases as well.

closes #1066

┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-178) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 4.0 beta 2

### CODE REVIEW

**Comment by SteveDonie** [comment]
Thanks for your pull request! The team will review this and add comments with a status update soon.

File: liquibase-core/src/main/java/liquibase/sqlgenerator/core/SetNullableGenerator.java [hunk 1]
```diff
@@ -74,6 +74,8 @@ public ValidationErrors validate(SetNullableStatement setNullableStatement, Data
                 nullableString = "";
             }
             sql = "ALTER TABLE " + database.escapeTableName(statement.getCatalogName(), statement.getSchemaName(), statement.getTableName()) + " MODIFY (" + database.escapeColumnName(statement.getCatalogName(), statement.getSchemaName(), statement.getTableName(), statement.getColumnName()) + " " + DataTypeFactory.getInstance().fromDescription(statement.getColumnDataType(), database).toDatabaseDataType(database) + nullableString + ")";
+        } else if (database instanceof FirebirdDatabase && !(database instanceof Firebird3Database)) {
+            sql = "UPDATE RDB$RELATION_FIELDS SET RDB$NULL_FLAG = " + (statement.isNullable() ? "1" : "NULL") + " WHERE RDB$RELATION_NAME = " + database.escapeTableName(statement.getCatalogName(), statement.getSchemaName(), statement.getTableName()) + " AND RDB$FIELD_NAME = " + database.escapeColumnName(statement.getCatalogName(), statement.getSchemaName(), statement.getTableName(), statement.getColumnName());
```
Comment (SteveDonie) [inline liquibase-core/src/main/java/liquibase/sqlgenerator/core/SetNullableGenerator.java:78]: Can you explain why this is referring to system tables and not just doing an `ALTER TABLE` statement?

Comment (Wallaby1999) [reply liquibase-core/src/main/java/liquibase/sqlgenerator/core/SetNullableGenerator.java:80]: Added a commit with a comment in the code, also referencing the official Firebird FAQ

**Comment by Wallaby1999** [comment]
As the resulting SQL is different for Firebird 3 databases than for the earlier versions it might be a good idea to separate the tests. As I do not know what is the best way to achieve this, I did not make any proposal. But I am happy to help when needed and when I get some advice how to do it

**Comment by SteveDonie** [comment]
@Wallaby1999 Can you clarify why you added the single quotes? The method database.escapeObjectName() should surround object names with quotes as needed.

**Comment by Wallaby1999** [comment]
When I played around a bit with Firebird3Database I got some test errors. Then I saw the generated statements on the console. And it showed:
UPDATE RDB$RELATION_FIELDS SET RDB$NULL_FLAG = 1 WHERE RDB$RELATION_NAME = state AND RDB$FIELD_NAME = abbreviation;
But it must be:
UPDATE RDB$RELATION_FIELDS SET RDB$NULL_FLAG = 1 WHERE RDB$RELATION_NAME = 'state' AND RDB$FIELD_NAME = 'abbreviation';


And in addition I just saw that I interchanged "1" and "NULL", which I corrected with my last commit fd99682

**Comment by Wallaby1999** [comment]
Shall I open a new issue or a new Pull Request for starting to integrate the Firebird3Database modifications?

**Comment by SteveDonie** [comment]
For the Firebird3 changes, if you are willing to work on that, please open a new issue and/or pull request. Thanks!
