### PR TITLE
Warning in case of missing liquibase files instead of throwing an exception

### LINKED ISSUE #2256: SkipMissingChangelogsSpringLiquibase
We have a big multi-module maven project, that each module is independent in terms of everything starting from Liquibase files to the database schema to entity, service, controller layers ... etc.  But at end of the day, we have one main module that includes all such files as :

```
### db.changelog-master.yaml
databaseChangeLog:
  - include:
      file: classpath:db/changelog/module1.xml
  - include:
      file: classpath:db/changelog/module2.xml
.......
.......
```
The point is, in development-time, the developer doesn't need to load all modules (each module is a maven profile, so one can exclude modules easily by just enabling/disabling profiles belonging to his own module)

Everything goes fine until we started the app, and Liquibase starts to complain about missing Liquibase configuration files. 😢 

So to fix the issue we have to add our own [SkipMissingChangelogsSpringLiquibase.java](https://gist.github.com/mhewedy/39094729975d9d73d11afad82af55788) and use it to configure spring Liquibase bean.

We wished that time such a tolerated mechanism exists as part of Liquibase in order not to "hack" it. 

_So My question here is can we have this [Code ](https://gist.github.com/mhewedy/39094729975d9d73d11afad82af55788)part of Liquibase so as to minimize the customization we (and maybe others) doing?_  (I can submit the PR 😉 )

### PR DESCRIPTION
**Pull request by mhewedy**
## Impact

- [ ] Bug fix (non-breaking change which fixes expected existing functionality)
- [x] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

This PR is adding support for to set up the option to whether thrown displays missing files as a warning or to keep throwing an exception as it does today based on a boolean flag set for the ChangeLog parser configuration (`WARN_OR_ERROR_ON_MISSING_CHANGELOGS`).

Fixes #2256

## Things to be aware of

- Changelog configuration added to the changelog parser to either determine to shows error as a warning or keep doing it as an exception. 

## Things to worry about

- None

## Additional Context

- Nothing

### CODE REVIEW

**Comment by nvoxland** [comment]
The new code would definitely have to be behind an if statement based on a configurable flag. That way the standard behavior of throwing an exception can remain the default, but people can choose "just warn" instead if they want. You'd add that flag to liquibase.ChangeLogParserConfiguration with a descriptive name

**Comment by mhewedy** [comment]
> The new code would definitely have to be behind an if statement based on a configurable flag. That way the standard behavior of throwing an exception can remain the default, but people can choose "just warn" instead if they want. You'd add that flag to liquibase.ChangeLogParserConfiguration with a descriptive name

Will give it a check this weekend

**Comment by mhewedy** [comment]
@nvoxland I've updated the PR based on your suggestions.

I tried to follow the `IOException(FileUtil.getFileNotFoundMessage())` to lead me to locations that need change.

Please let me know if it needs enhancements ...

**Comment by MalloD12** [comment]
Hi @mhewedy, 

Thanks for taking care of this change. I'm just curious about the state of this PR, is it in "Draft" state because you are expecting to commit some more changes or is it ready to review? 

Thanks,
Daniel.

File: liquibase-core/src/main/java/liquibase/change/core/CreateProcedureChange.java [hunk 1]
```diff
@@ -303,7 +305,12 @@ public SqlStatement[] generateStatements(Database database) {
                 try {
                     InputStream stream = openSqlStream();
                     if (stream == null) {
-                        throw new IOException(FileUtil.getFileNotFoundMessage(path));
+                        if (ChangeLogParserConfiguration.WARN_ON_MISSING_CHANGELOGS.getCurrentValue()) {
```
Comment (MalloD12) [inline liquibase-core/src/main/java/liquibase/change/core/CreateProcedureChange.java:308]: I think it would be good to extract this piece of code into a function of AbstractChange as both (CreateProcedure and CreateView extend of it), as something like this:
```
public ByteArrayInputStream returnEmptyResourceIfMissingFile(String path) {
    if (ChangeLogParserConfiguration.WARN_ON_MISSING_CHANGELOGS.getCurrentValue()) {
        Scope.getCurrentScope().getLog(getClass()).warning(FileUtil.getFileNotFoundMessage(path));
        return new ByteArrayInputStream(FileUtil.EMPTY_FILE.getBytes(StandardCharsets.UTF_8));
    }
    else {
        throw new IOException(FileUtil.getFileNotFoundMessage(path));
    }
}
```
So then if we have it available there if any other object needs to execute the same logic,  or if they need to override it to apply any other variation of it.

File: liquibase-core/src/main/java/liquibase/command/core/InternalExecuteSqlCommandStep.java [hunk 2]
```diff
@@ -61,10 +64,16 @@ public void run(CommandResultsBuilder resultsBuilder) throws Exception {
         } else {
             final PathHandlerFactory pathHandlerFactory = Scope.getCurrentScope().getSingleton(PathHandlerFactory.class);
             Resource resource = pathHandlerFactory.getResource(sqlFile);
-            if (!resource.exists()){
-                throw new LiquibaseException(FileUtil.getFileNotFoundMessage(sqlFile));
+            if (!resource.exists()) {
```
Comment (MalloD12) [inline liquibase-core/src/main/java/liquibase/command/core/InternalExecuteSqlCommandStep.java:67]: Similarly to my `CreateProcedure` comment, I would put this logic as a function of `AbstractCommandStep` class as something like this:
```
public String returnEmptyResourceIfMissingFile(String sqlFile) {
    if (ChangeLogParserConfiguration.WARN_ON_MISSING_CHANGELOGS.getCurrentValue()) {
        Scope.getCurrentScope().getLog(getClass()).warning(FileUtil.getFileNotFoundMessage(path));
        return FileUtil.EMPTY_FILE;
    }
    else {
        throw new LiquibaseException(FileUtil.getFileNotFoundMessage(sqlFile));
    }
}
```

File: liquibase-core/src/main/java/liquibase/resource/ResourceAccessor.java [hunk 3]
```diff
@@ -159,7 +158,12 @@ default SortedSet<String> list(String relativeTo, String path, boolean recursive
     default Resource getExisting(String path) throws IOException {
         Resource resource = get(path);
         if (!resource.exists()) {
-            throw new FileNotFoundException(FileUtil.getFileNotFoundMessage(path));
+            if (ChangeLogParserConfiguration.WARN_ON_MISSING_CHANGELOGS.getCurrentValue()) {
```
Comment (MalloD12) [inline liquibase-core/src/main/java/liquibase/resource/ResourceAccessor.java:161]: Similarly to my previous comments, I would suggest extracting this logic as a function on this same interface.

File: liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java [hunk 4]
```diff
@@ -839,19 +841,31 @@ public void configureFieldsAndValues() throws MojoExecutionException, MojoFailur
         if (propertyFile != null) {
             getLog().info("Parsing Liquibase Properties File");
             getLog().info("  File: " + propertyFile);
-            try (InputStream is = handlePropertyFileInputStream(propertyFile)) {
+            try (InputStream _is = handlePropertyFileInputStream(propertyFile)) {
```
Comment (MalloD12) [inline liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java:844]: Similarly to my previous comments, I would suggest extracting this logic as a function of `AbstractLiquibaseMojo` class, similarly as suggested for `CreateProcedure` change.

File: liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java [hunk 5]
```diff
@@ -839,19 +841,31 @@ public void configureFieldsAndValues() throws MojoExecutionException, MojoFailur
...
+                    }
                 }
 
                 parsePropertiesFile(is);
                 getLog().info(MavenUtils.LOG_SEPARATOR);
             } catch (IOException e) {
                 throw new UnexpectedLiquibaseException(e);
             }
-            try (InputStream is = handlePropertyFileInputStream(propertyFile)) {
+            try (InputStream _is = handlePropertyFileInputStream(propertyFile)) {
```
Comment (MalloD12) [inline liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java:860]: I would suggest here moving below lines into the above try and remove this piece of code as except these lines it looks like the same:
```
LiquibaseConfiguration liquibaseConfiguration = Scope.getCurrentScope().getSingleton(LiquibaseConfiguration.class);
                final DefaultsFileValueProvider fileProvider = new DefaultsFileValueProvider(is, "Property file "+propertyFile);
                liquibaseConfiguration.registerProvider(fileProvider);
```

**Comment by MalloD12** [comment]
Hi @mhewedy, I have started reviewing your code and have left some comments/suggestions. Please let me know if you have any questions/concerns with any of them.

Thanks,
Daniel.

**Comment by mhewedy** [comment]
> Hi @mhewedy, I have started reviewing your code and have left some comments/suggestions. Please let me know if you have any questions/concerns with any of them.
> 
> Thanks, Daniel.

Thansk... I will update the PR accordingly

**Comment by mhewedy** [comment]
> Hi @mhewedy, I have started reviewing your code and have left some comments/suggestions. Please let me know if you have any questions/concerns with any of them.
> 
> Thanks, Daniel.

Thansk... I will update the PR accordingly

File: liquibase-core/src/main/java/liquibase/parser/ChangeLogParserConfiguration.java [hunk 6]
```diff
@@ -41,6 +41,10 @@ public class ChangeLogParserConfiguration implements AutoloadedConfigurations {
                 .setDefaultValue(ChangelogParseMode.STRICT)
                 .build();
 
+        WARN_ON_MISSING_CHANGELOGS = builder.define("warnOnMissingChangeLogs", Boolean.class)
```
Comment (MalloD12) [inline liquibase-core/src/main/java/liquibase/parser/ChangeLogParserConfiguration.java:44]: Would you mind to also rename this variable to `WARN_OR_ERROR_ON_MISSING_CHANGELOGS`? Since if the default value set is `true` it will return an error, instead of a warning.

File: liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java [hunk 7]
```diff
@@ -839,20 +841,13 @@ public void configureFieldsAndValues() throws MojoExecutionException, MojoFailur
         if (propertyFile != null) {
             getLog().info("Parsing Liquibase Properties File");
             getLog().info("  File: " + propertyFile);
-            try (InputStream is = handlePropertyFileInputStream(propertyFile)) {
+            try (InputStream _is = handlePropertyFileInputStream(propertyFile)) {
```
Comment (mhewedy) [inline liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java:844]: I feel I am not doing the write thing here, as `handlePropertyFileInputStream` will throw an exception if the `propertyFile` does not exist.

What do you suggest here @MalloD12

Comment (MalloD12) [reply liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java:844]: Hi @mhewedy,

First, let me thank you for applying my previous review comments. Now, regarding this question I think what you need to do here is also catch `MojoFailureException` which will be thrown by `handlePropertyFileInputStream()` in case the file does not exists. Also, I think you can either remove `_is` or `is` variable declaration, because `_is` is defined in the try and afterwards `is` is defined and being assigned with `_is` value.

Thanks,
Daniel.

Comment (mhewedy) [reply liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java:844]: Actually, I found that `handlePropertyFileInputStream` calls  `ResouceAccessor#getExisting` which will calls `returnEmptyResourceIfMissingFile`.

So we need no handling here.. Do you agree?

Comment (MalloD12) [reply liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java]: That's correct, although I still think we should add the `MojoFailureException` to the catch block in the `configureFieldsAndValues` method. Rest of the things looks good to me. 

Thanks,
Daniel.

Comment (mhewedy) [reply liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java]: Ok, will do that... 
Should I add a call to `returnEmptyResourceIfMissingFile` in the catch block?

Comment (MalloD12) [reply liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java]: I meant just doing something like:  `catch (IOException  | MojoFailureException e)`. And I think doing that you can also remove `MojoFailureException` from the method signature.

Thanks,
Daniel.

Comment (mhewedy) [reply liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java]: Aha, I got it...
It is updated now

**Comment by XDelphiGrl** [comment]
@filipelautert and @MalloD12 - 

Here's what I found in my investigation of the functional test failures.
* Test failures are for any Maven tests requiring a Pro license.
  * The test I debugged is: `updateTests.updatePro` (with `@DataProvider(indices = {4})` to run only one Maven test case).
  * I stopped the test at a break point at line 121 to configure a database and populate the project.
  * The command I executed manually to better debug is:
```
mvn -X liquibase:update  -Dliquibase.propertyFile=./liquibase.properties -Dliquibase.changeLogFile=changelog.xml -Dliquibase.labels=community,pro >> mvn1039-log.txt
```

Looking at the logs, I can see that Liquibase Maven is not reading the license key from the provided liquibase.properties file. 
```
[DEBUG] No configuration value for liquibase.licenseKey found
[DEBUG] No configuration value for liquibase.pro.licenseKey found
```

When I provide the license key in the `<liquibaseProLicenseKey>` property in the pom.xml file, the license is discovered, loaded and used; this makes the update pass where it failed with Pro validation errors using just the properties file.

```
[DEBUG] Found 'liquibase.licenseKey' configuration of 'license starting with ABwwGgQUPo'
    scoped value 'liquibase.licenseKey' of '*****'
```

This error is not happening with the master version of liquibase-maven-plugin. I believe the failures are related to this PR.

cc @suryaaki2

**Review by MalloD12 — APPROVED** [review]

**Comment by mhewedy** [comment]
> Hi @mhewedy, I just wanted to let you know I had to revert the changes we have made in the `AbstractLiquibaseMojo` because these changes were causing `liquibase.properties` files to not be set properly and it was making fail some of our functional tests suites which were executed using Liquibase MVN extension.
> 
> Changes are looking good to me. I'm going to approve this PR now but I'll move it to the code review state after doing some manual test here, so then other members of the team can review it too. I'll post my review comment afterwards.
> 
> Any comments/suggestions/feedback you might have are more than welcome. Again, thank you for your contribution! Hope we can release this change soon.

Thanks for letting me know.

Looking forward to see it merged.

**Comment by mhewedy** [comment]
Closed by mistake!

**Comment by mhewedy** [comment]
@filipelautert Any updates on this?

**Comment by MalloD12** [comment]
> @filipelautert Any updates on this?

Hi @mhewedy yes, I am still working on this. On Friday after performing some manual testing with @nvoxland assistance we realised this configuration support wasn't working as expected for CreateProcedure, which would require some more changes/refactoring to do. Looking again at #2256 this configuration support seems more appropriate for **include** tag, and at the moment I'm working on removing current behaviour from CreateProcedure/CreateView, moving include tag logic at a higher level, plus some others refactoring. I'm expecting to push this commit today and I would very much appreciate you look at it and share any feedback/concerns you might have. 

Thanks,
Daniel.

**Comment by mhewedy** [comment]
> > @filipelautert Any updates on this?
> 
> Hi @mhewedy yes, I am still working on this. On Friday after performing some manual testing with @nvoxland assistance we realised this configuration support wasn't working as expected for CreateProcedure, which would require some more changes/refactoring to do. Looking again at #2256 this configuration support seems more appropriate for **include** tag, and at the moment I'm working on removing current behaviour from CreateProcedure/CreateView, moving include tag logic at a higher level, plus some others refactoring. I'm expecting to push this commit today and I would very much appreciate you look at it and share any feedback/concerns you might have.
> 
> Thanks, Daniel.

Thanks for your update.

**Comment by MalloD12** [comment]
Hi @mhewedy, 

I just want to let you know I have already pushed some changes and made some updates as I said earlier. I think these changes are good enough to fix #2256. Could you please review it and share any feedback/concerns you might have?  If there are any other change objects which might need to also follow the same logic, I think the best approach would be to address the required changes in a separate PR. If you are happy with this, as soon as all checks are green I can move to "code review" so others team members can also review this code.

Thanks,
Daniel.

File: liquibase-core/src/main/java/liquibase/parser/ChangeLogParserConfiguration.java [hunk 8]
```diff
@@ -12,7 +12,7 @@ public class ChangeLogParserConfiguration implements AutoloadedConfigurations {
     public static final ConfigurationDefinition<Boolean> USE_PROCEDURE_SCHEMA;
     public static final ConfigurationDefinition<MissingPropertyMode> MISSING_PROPERTY_MODE;
     public static final ConfigurationDefinition<ChangelogParseMode> CHANGELOG_PARSE_MODE;
-    public static final ConfigurationDefinition<Boolean> WARN_OR_ERROR_ON_MISSING_CHANGELOGS;
+    public static final ConfigurationDefinition<Boolean> WARN_OR_ERROR_ON_MISSING_INCLUDE_FILE;
```
Comment (mhewedy) [inline liquibase-core/src/main/java/liquibase/parser/ChangeLogParserConfiguration.java]: The name now is much more expressive, thanks.

**Comment by mhewedy** [comment]
So you remove the logic from everywhere and adding to `DatabaseChangeLog`. correct?

I see code much cleaner now and change is centralized in one place.

LGTM

File: liquibase-core/src/main/java/liquibase/parser/ChangeLogParserConfiguration.java [hunk 9]
```diff
@@ -40,7 +40,7 @@ public class ChangeLogParserConfiguration implements AutoloadedConfigurations {
                 .setDefaultValue(ChangelogParseMode.STRICT)
                 .build();
 
-        WARN_OR_ERROR_ON_MISSING_INCLUDE_FILE = builder.define("warnOrErrorOnMissingInclude", Boolean.class)
+        WARN_ON_MISSING_INCLUDE_FILE = builder.define("warnOnMissingInclude", Boolean.class)
```
Comment (mhewedy) [inline liquibase-core/src/main/java/liquibase/parser/ChangeLogParserConfiguration.java:43]: And this even shorter

**Comment by MalloD12** [comment]
> So you remove the logic from everywhere and adding to `DatabaseChangeLog`. correct?
> 
> I see code much cleaner now and change is centralized in one place.
> 
> LGTM, Thanks!

Hi @mhewedy, yeah that is correct. Again, as I mentioned before if you guys realised later on you need this support in any other specific object, then I think the best would be to create a separate issue/PR for it.

Thanks,
Daniel.

**Review by filipelautert — CHANGES_REQUESTED** [review]

File: liquibase-core/src/main/java/liquibase/resource/EmptyResource.java [hunk 10]
```diff
@@ -0,0 +1,53 @@
...
+import java.io.ByteArrayInputStream;
+import java.io.IOException;
+import java.io.InputStream;
+import java.io.OutputStream;
+import java.net.URI;
+
+/**
+ * Used to represent an empty file
+ */
+public final class EmptyResource implements Resource {
```
[the remark this answers is not in the document]
Comment (MalloD12) [reply liquibase-core/src/main/java/liquibase/resource/EmptyResource.java]: `EmptyResource` class removed.

File: liquibase-core/src/main/java/liquibase/change/core/CreateViewChange.java [hunk 11]
```diff
@@ -235,27 +235,27 @@ public SqlStatement[] generateStatements(Database database) {
             fullDefinition = this.fullDefinition;
         }
```
[the remark this answers is not in the document]
Comment (MalloD12) [reply liquibase-core/src/main/java/liquibase/change/core/CreateViewChange.java]: Reset as it's in master.

File: liquibase-core/src/main/java/liquibase/parser/ChangeLogParserConfiguration.java (hunk 8 above)
Comment (MalloD12) [reply liquibase-core/src/main/java/liquibase/parser/ChangeLogParserConfiguration.java]: Hey @mhewedy, I just want to let you know as you can see on the latest changes I have updated this configuration one more time based on the team's code review. I have renamed it to `ON_MISSING_INCLUDE_FILE`, and also changed it to be set with an Enumeration which for now only has WARN and FAIL values. I think it will now be even more self-explainable. I hope you are happy with these changes.  

Thanks, 
Daniel.

**Review by nvoxland — APPROVED** [review]

**Review by filipelautert — APPROVED** [review]
Nice, thanks for the code contribution @mhewedy !

**Comment by mhewedy** [comment]
Any updates on this?

**Comment by MalloD12** [comment]
Hi @mhewedy,

Thank you for following up on this. As you can see this PR has been approved for some members of the team, but as these changes are also impacting another of our projects we still need to get some more approval. I want to apologize for the delay this is taking. Last week has been pretty busy for some of our team members, I hope we can get their approval soon so then we can finally include this PR in one of our next releases. 

Thanks, 
Daniel.

**Comment by mhewedy** [comment]
Thanks for updates.

**Review by XDelphiGrl — COMMENTED** [review]
This PR provides users the capability to configure Liquibase behavior when an included file is not located. The mechanism is a new GLOBAL property, `ON_MISSING_INCLUDE_FILE`. 
* Valid configurations are FAIL and WARN.
* Default is FAIL (consistent with Liquibase behavior prior to this change).
* Functional test execution is successful.
* Test harness execution failed for one database platform due to an environmental issue; this is not a blocker for this PR to merge.
* No additional testing necessary.

File: liquibase-core/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy [hunk 12]
```diff
@@ -494,4 +500,30 @@ create view sql_view as select * from sql_table;'''
         "D:\\a\\liquibase\\DBDocTaskTest.xml" | "a/liquibase/DBDocTaskTest.xml"
     }
 
+    def "warning message is logged when changelog include fails because file does not exist"() {
```
Comment (XDelphiGrl) [inline liquibase-core/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy:503]: I would like us to add a test for `ChangeLogParserConfiguration.MissingIncludeConfiguration.FAIL`.  I realize this should result in the default/existing behavior but without a test we cannot be sure that remains true over time.

CC @mhewedy @MalloD12

**Review by XDelphiGrl — CHANGES_REQUESTED** [review]
See [https://github.com/liquibase/liquibase/pull/3081/files#r1073858377](https://github.com/liquibase/liquibase/pull/3081/files#r1073858377) for requested change. 

CHANGES REQUESTED

File: liquibase-core/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy (hunk 12 above)
Comment (MalloD12) [reply liquibase-core/src/test/groovy/liquibase/changelog/DatabaseChangeLogTest.groovy:533]: Updated existent `"include fails if file does not exist"` test to assert `ChangeLogParserConfiguration.ON_MISSING_INCLUDE_FILE.getCurrentValue() == ChangeLogParserConfiguration.MissingIncludeConfiguration.FAIL`

Thanks Erz!

**Review by XDelphiGrl — APPROVED** [review]
In some cases, there are valid reasons for a file included in a changelog to be missing. This PR allows users to configure a new global property, `ON_MISSING_INCLUDE_FILE` to throw a warning instead of an error if an included file is missing. 
**DEFAULT VALUE**: FAIL (maintains backwards compatibility)
**CONFIGURATION VALUES**: WARN, FAIL

* Functional tests passing.
* Test harness execution failing for unrelated reason.
* New unit tests added for WARN and FAIL.
* No additional testing required.

APPROVED

**Comment by mhewedy** [comment]
Hence this new property `onMissingInclude` is not exposed via SpringLiquibase, then the only option to configure in springboot project is to introduce `liquibase.properties` file, correct?

**Comment by mhewedy** [comment]
> > Hence this new property `onMissingInclude` is not exposed via SpringLiquibase, then the only option to configure in springboot project is to introduce `liquibase.properties` file, correct?
> 
> Hi @mhewedy, that's correct as far as I know that's the only way to set up this property.
> 
> Thanks, Daniel.

Thanks
