### PR TITLE
Apply SQL visitors to prepared SQL

### LINKED ISSUE #5098: SQL visitors aren't applied to prepared SQL
### Search first

- [X] I searched and no similar issues were found

### Description

Some changes, such as `insert`, `update`, `loadData and possibly `loadUpdateData` can generate prepared SQL for update and/or rollback. But when this happens SQL visitors aren't applied. Incidentally, prepared SQL is also not logged.

### Steps To Reproduce

db/changelog/db.changelog-master.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
    xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
        https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
        http://www.liquibase.org/xml/ns/dbchangelog-ext
        https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd">
  <preConditions>
    <dbms type="h2"/>
  </preConditions>

  <changeSet id="1" author="liquibase">
    <createTable tableName="person">
      <column name="key" type="int">
        <constraints nullable="false" primaryKey="true"/>
      </column>
      <column name="firstname" type="nvarchar(50)">
        <constraints nullable="false"/>
      </column>
      <column name="lastname" type="nvarchar(50)">
        <constraints nullable="false"/>
      </column>
    </createTable>
    <modifySql>
      <replace replace="&quot;KEY&quot;" with="&quot;key&quot;"/>
    </modifySql>
  </changeSet>

  <changeSet id="2" author="liquibase">
    <loadData tableName="person" file="names.csv" relativeToChangelogFile="true">
      <column name="key" type="NUMERIC"/>
      <column name="first" type="STRING"/>
      <column name="last" type="STRING"/>
    </loadData>
    <rollback>
      <delete tableName="person"/>
    </rollback>
    <modifySql applyToRollback="true">
      <replace replace="&quot;KEY&quot;" with="&quot;key&quot;"/>
    </modifySql>
  </changeSet>

  <changeSet id="3" author="liquibase">
    <insert tableName="person">
      <column name="key" valueNumeric="3"/>
      <column name="first" value="nathan"/>
      <column name="last" value="voxland"/>
    </insert>
    <rollback>
      <delete tableName="person">
        <where>:name = :value</where>
        <whereParams>
          <param name="key" valueNumeric="3"/>
        </whereParams>
      </delete>
    </rollback>
    <modifySql applyToRollback="true">
      <replace replace="&quot;KEY&quot;" with="&quot;key&quot;"/>
    </modifySql>
  </changeSet>
</databaseChangeLog>
```

db/changelog/names.csv:
```
key,first,last
0,john,doe
1,eric,smith
2,cat,jones
```

### Expected/Desired Behavior

SQL visitors are applied to prepared SQL in the same manner that they are applied to raw SQL.

### Liquibase Version

4.24.0

### Database Vendor & Version

Any

### Liquibase Integration

Any

### Liquibase Extensions

None

### OS and/or Infrastructure Type/Provider

Any

### Additional Context

The example is based on H2.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

### PR DESCRIPTION
**Pull request by mches**
## Impact

- [x] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 

## Description

Apply SQL visitors to, and log, prepared SQL.

Fixes #5098.

## Things to be aware of

New API `protected String applyVisitors(String sql, List<SqlVisitor> sqlVisitors)` on `ExecutablePreparedStatementBase` is exposed to subclasses.

## Things to worry about

An extension which extends `ExecutablePreparedStatementBase` or implements `ExecutablePreparedStatement` could require some changes to adopt the the desired behavior.

### CODE REVIEW

File: liquibase-standard/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java [hunk 1]
```diff
@@ -121,6 +129,18 @@ public void execute(PreparedStatementFactory factory) throws DatabaseException {
         }
     }
 
+    protected String applyVisitors(String sql, List<SqlVisitor> sqlVisitors) {
```
Comment (filipelautert) [inline liquibase-standard/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java:132]: Should this method be private so we don't need to worry about overrides? As I verified the extensions and none of them is extending this class (only mssql extension makes reference to this class but not by extending it).

**Review by filipelautert — CHANGES_REQUESTED** [review]

File: liquibase-standard/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java (hunk 1 above)
Comment (mches) [reply liquibase-standard/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java:132]: The downside of having it private is that any subclass that overrides the non-final method `liquibase.statement.ExecutablePreparedStatementBase#execute` would have to reimplement the this method.

**Review by filipelautert — APPROVED** [review]

**Review by rberezen — APPROVED** [review]

**Review by wwillard7800 — APPROVED** [review]
