### PR TITLE
Fixes issue #4415: "Wrong DDL syntax CREATE SEQUENCE ... AS ..."

### LINKED ISSUE #4415: SQL Anywhere: Wrong DDL syntax `CREATE SEQUENCE ... AS ...`
### Search first

- [X] I searched and no similar issues were found

### Description

Using latest SQL Anywhere 17.0.11-7254 as a *standalone* engine (**without** using testcontainers) I am trying to execute integration tests, and this is the result:
```
[ERROR] liquibase.dbtest.asany.SybaseASAIntegrationTest.testRerunDiffChangeLog  Time elapsed: 24.851 s  <<< ERROR!
liquibase.exception.CommandExecutionException:
liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset changelogs/common/common.tests.changelog.xml::seq-test-datatype::flautert:
     Reason: liquibase.exception.DatabaseException: [SAP][JDBC Driver][SQL Anywhere]Syntaxfehler bei 'AS' in Zeile 1  [Failed SQL: (-131) CREATE SEQUENCE lbuser.seqtestdatatypeonall AS int]
```
Apparently Liquibase expects that SQL Anywhere supports the syntax `CREATE SEQUENCE ... AS ...`, but according to the [latest product manual](https://help.sap.com/docs/SAP_SQL_Anywhere/93079d4ba8e44920ae63ffb4def91f5b/3be47d496c5f1014bf06bb7791ce7a38.html?locale=en-US&q=CREATE%20SEQUENCE) SQL Anywhere is (and I assume, it ever was) unable to deal with the `AS ...` clause:
>CREATE [ OR REPLACE ] SEQUENCE [ owner .] sequence-name
[ INCREMENT BY signed-integer ]
[ START WITH signed-integer ]
[ MINVALUE signed-integer | NO MINVALUE ]
[ MAXVALUE signed-integer | NO MAXVALUE ]
[ CACHE integer | NO CACHE ]
[ CYCLE | NO CYCLE ]

### Steps To Reproduce

```bash
dbinit -dba lbuser,LiquibasePass1 liquibase
```
```liquibase.sdk.local.yaml
liquibase:
  sdk:
    testSystem:
      test: asany

      asany:
        url: jdbc:sqlanywhere:DBF=liquibase.db
```
```bash
mvn verify -Dtest=SybaseASAIntegrationTest -Dsurefire.failIfNoSpecifiedTests=false
```

### Expected/Desired Behavior

The IT passes successfully.

### Liquibase Version

master

### Database Vendor & Version

SAP SQL Anywhere 17.0.11

### Liquibase Integration

N/A

### Liquibase Extensions

N/A

### OS and/or Infrastructure Type/Provider

Windows 10 Pro (German)

### Additional Context

Standalone engine / Without Testcontainers

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

### PR DESCRIPTION
**Pull request by mkarg**
Fixes #4415 

## Impact

- [x] Bug fix (non-breaking change which fixes expected existing functionality)
- [x] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

In addition to the original issue description, not only the reported bug is fixed, but also the support for CREATE SEQUENCE was extended in alignment with the latest product manual.

## Things to be aware of

N/A

## Things to worry about

N/A

## Additional Context

N/A

### CODE REVIEW

**Comment by mkarg** [comment]
@filipelautert This PR is needed to pass ITs on SQL Anywhere. I would be happy if you could find the time to review it.

**Comment by mkarg** [comment]
Just found a typo. Reverting to draft until I have fixed it.

**Comment by filipelautert** [comment]
Hello @mkarg ! Please let me know when it's ok so i'll build and review it 👍

**Comment by mkarg** [comment]
> Hello @mkarg ! Please let me know when it's ok so i'll build and review it 👍

@filipelautert Thank you for your kind patience. Typo is fixed now, so test is passing again. Thank you for reviewing it! :-)

**Review by filipelautert — APPROVED** [review]
This PR fixes  CREATE SEQUENCE for SQL Anywhere

File: liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java [hunk 1]
```diff
@@ -97,9 +97,9 @@ public Sql[] generateSql(CreateSequenceStatement statement, Database database, S
         }
 
         if (statement.getCacheSize() != null) {
-            if (database instanceof OracleDatabase || database instanceof Db2zDatabase || database instanceof PostgresDatabase || database instanceof MariaDBDatabase) {
+            if (database instanceof OracleDatabase || database instanceof Db2zDatabase || database instanceof PostgresDatabase || database instanceof MariaDBDatabase || database instanceof SybaseASADatabase) {
                 if (BigInteger.ZERO.equals(statement.getCacheSize())) {
-                    if (database instanceof OracleDatabase) {
+                    if (database instanceof OracleDatabase || database instanceof SybaseASADatabase) {
```
Comment (rberezen) [inline liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java:102]: hello @mkarg! 
Could you please verify if the correct syntax for SQL Anywhere is "NO CACHE" instead of "NOCACHE"? I would greatly appreciate your assistance. You can refer to the following link for more information:
https://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.help.sqlanywhere.12.0.1/dbreference/create-sequence-statement.html
cc @filipelautert

Comment (mkarg) [reply liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java:102]: @rberezen Good catch! According to the manuals, it is `NO CACHE`. I will modify the PR.

Comment (mkarg) [reply liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java]: @rberezen Syntax is corrected in https://github.com/liquibase/liquibase/pull/4417/commits/32a881968982296926472c24d667371bdbb25939, according to latest SAP documentation (https://help.sap.com/docs/SAP_SQL_Anywhere/93079d4ba8e44920ae63ffb4def91f5b/3be47d496c5f1014bf06bb7791ce7a38.html?locale=en-US&q=CREATE%20SEQUENCE). Unit test will follow ASAP.

Comment (mkarg) [reply liquibase-standard/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java]: @rberezen Thank you for your kind patience. You can now find the unit test in 6fe525b974821068da73740c8d9ec43a59287627.

**Comment by rberezen** [comment]
@mkarg thank you very much for your help! 
This pull request resolves an issue where the AS clause was mistakenly added to a SQL statement for the SQL Anywhere Database, which is not supported by SQL Anywhere.

- Functional and test harness executions passing.
- New unit test added.
- No additional testing required.

APPROVED

**Review by rberezen — APPROVED** [review]
