### PR TITLE
Addition of liquibase.update() Enhancement Request #1614

### LINKED ISSUE #1614: Addition of liquibase.update()
## Environment
**Liquibase Version**: 4.2.2

**Liquibase Integration & Version**: Spring Boot 2.2.2

**Liquibase Extension(s) & Version**: N/A

**Database Vendor & Version**: HSQLDB

**Operating System Type & Version**: Win 10

## Description
This is a request for enahancement.

I tried to implement liquibase update programatically in Spring Boot application and I found that `liquibase.Liquibase.update()` requires a parameter(s), but it is accepting `""` as well as `null`, so I believe there should be version without parameter provided. It's confusing that context is required, while from command line for example it is not.

## Steps To Reproduce
```java
File file = changelogResource.getFile();
File parentFile = file.getParentFile();
Liquibase liquibase = new Liquibase(file.getName(), new FileSystemResourceAccessor(parentFile), getDatabase());
liquibase.update((String)null);
```

## Actual Behavior
`liquibase.Liquibase.update()` requires a parameter(s)

## Expected/Desired Behavior
There will be `liquibase.Liquibase.update()` version without a parameter in API.

## Screenshots (if appropriate)
N/A

## Additional Context
N/A

### PR DESCRIPTION
**Pull request by Betlista**
Added `.update()`

* some JavaDocs.

## Environment
**Liquibase Version**: 4.3.0

**Liquibase Integration & Version**: maven

**Liquibase Extension(s) & Version**: N/A

**Database Vendor & Version**: N/A

**Operating System Type & Version**: Win 10

## Pull Request Type

* [ ] Bug fix (non-breaking change which fixes an issue.)
* [x] Enhancement/New feature (non-breaking change which adds functionality) closes #1614
* [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
Described in issue itself.

## Steps To Reproduce
Described in issue itself.

## Actual Behavior
Described in issue itself.

## Expected/Desired Behavior
Described in issue itself.

## Screenshots (if appropriate)
N/A

## Additional Context
N/A

## Fast Track PR Acceptance Checklist:

* [x] Build is successful and all new and existing tests pass
* [x] Added [Unit Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)
* [ ] Added [Integration Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)
* [ ] Added [Test Harness Test(s)](https://github.com/liquibase/liquibase-test-harness/pulls)
* [ ] Documentation Updated

## Need Help?
Come chat with us on our [discord channel](https://discord.com/channels/700506481111597066/700506481572839505)

### CODE REVIEW

**Comment by molivasdat** [comment]
Hi @Betlista 
Thanks for providing this PR.

Here’s what happens next:

A member of the Liquibase team will take a look at your contribution and may suggest: 

- Changes based on [guidelines for PR submission](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/How+to+Contribute+Code+to+Liquibase+Core)
- Additional tests ([unit ](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)and/or [integration](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)) and/or Test Harness Tests
- Provide other feedback, like requesting changes. 

The PR will be prioritized according to our internal development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.

**Review by nvoxland — APPROVED** [review]
Thanks for the changes, @Betlista 

I hadn't originally had the no-arg update() in order to force people to be thinking about context/label usage. But, that's probably an unneeded force to think about and adding the extra function is good. The extra javadocs are good as well.

Code review and test results:

Things to be aware of:
- Adds a method we are not using, only 3rd party code
- Failure in test-harness is not related to change

Things to worry about:
- Nothing

**Review by suryaaki2 — APPROVED** [review]

File: liquibase-core/src/main/java/liquibase/command/core/InternalSnapshotCommandStep.java [hunk 1]
```diff
@@ -112,19 +112,15 @@ public static String printSnapshot(CommandScope commandScope, CommandResults sna
...
 
     public static void logUnsupportedDatabase(Database database, Class callingClass) {
         if (LicenseServiceUtils.isProLicenseValid()) {
             if (!(database instanceof MSSQLDatabase
                     || database instanceof OracleDatabase
                     || database instanceof MySQLDatabase
                     || database instanceof DB2Database
-                    || database instanceof PostgresDatabase)) {
+                    || database instanceof PostgresDatabase
+                    || database.getShortName().equalsIgnoreCase("snowflake"))) { //TODO: Update to use SnowflakeDatabase once the liquibase-snowflake module is fully integrated into liquibase-core
```
Comment (XDelphiGrl) [inline liquibase-core/src/main/java/liquibase/command/core/InternalSnapshotCommandStep.java:123]: Can the comment here be removed now that we support Snowflake is integrated into liquibase-core?

**Review by XDelphiGrl — APPROVED** [review]
Fix allows integrations to call liquibase update without requiring contexts and/or labels.
* Adds Java docs to several methods.
* Removes duplicated logUnsupportedDatabase method from SnapshotCommandStep.java, calling the method from InternalSnapshotCommand.java instead.
* Tests extended to validate communication with Hub using an update that does not pass contexts and/or labels.
* No additional testing required.

APPROVED

Note: Test failure in harness related to environment setup failure; not related to this change.

File: liquibase-core/src/main/java/liquibase/command/core/InternalSnapshotCommandStep.java (hunk 1 above)
Comment (nvoxland) [reply liquibase-core/src/main/java/liquibase/command/core/InternalSnapshotCommandStep.java:123]: It can be, but we'll deal with that in a separate change since it's unrelated to this one.

**Comment by tabbyf00** [comment]
Thanks for your PR submission! We just finished reviewing and merging it into the [4.17.0 release](https://github.com/liquibase/liquibase/releases/tag/v4.17.0) on October 10, 2022. When you get a chance, could you please Star the [Liquibase project](https://github.com/liquibase/liquibase)? The star button is in the upper right corner of the screen.
