### PR TITLE
Fix CheckSum generation issues + improvements 

### LINKED ISSUE #3549: SQL checksum not resilient to all formatting changes
## Description

When checksuming SQL based changesets like <sql> and <sqlFile> and <createProcedure> we run it through `liquibase.change.AbstractSQLChange.NormalizatingStream` which smooths out non-significant differences in the SQL.

For example, `create table test (id int)` and `create   table   test (id   int)` should generate the same checksum. 

That way, when editors or users reformat their SQL to make it more readable it's not going to keep them from deploying the changelog due to checksum errors. Same reason the checksum logic for other change types are not dependent on the XML formatting.

HOWEVER there are some semantically equivalent SQL which still generate different checksums.

**UPDATE**:  As part of this issue we are also going to update checksum generation logic to avoid including `contexts-filter`, `labels-filter`, and `dbms`.

## Steps To Reproduce

Run a  changelog with a <sql> tag in it, and keep running it against the same database but change the formatting of the SQL from one run to the next.

I saw that adding whitespace gets to be a problem. For example, `create table test (id int)` should be the same as `create table test ( id int )` but it was not. It should also be the same as `create table test (\nid int\n)` but was not.

Are there other ways can formatting change and still generate different checksums? Or is it just a "adding whitespace" problem?

## Additional Context

The impact to existing users need to be taken into account. I'm suspicious this will require a new checksum version, but we'll have to see what the actual required changes are.

### PR DESCRIPTION
**Pull request by MalloD12**
## Impact

- [x] Bug fix (non-breaking change which fixes expected existing functionality)
- [x] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

Checksum generation logic has been updated to fix some issues like avoiding considering some characters like white spaces, indentation, new line, etc when generating a checksum. Also, as part of these changes we will start ignoring contexts-filters, labels and dbms, as well as some specific properties for some objects (for example CreateProcedure, CreateView, etc) like path, encoding, relativeToChangeLog, etc. 

Fixes #3549 

## Things to be aware of
This PR cannot be merged until the [Liquibase internal] DAT-13285 is complete.

## Additional Context

- Nothing

### CODE REVIEW

**Comment by nvoxland** [comment]
The `Checksum.CURRENT_CHECKSUM_ALGORITHM_VERSION` version needs to be updated to 9 for sure with this change.

**Comment by MalloD12** [comment]
> The `Checksum.CURRENT_CHECKSUM_ALGORITHM_VERSION` version needs to be updated to 9 for sure with this change.

Done.

File: liquibase-core/src/main/java/liquibase/change/AbstractSQLChange.java [hunk 1]
```diff
@@ -282,7 +282,6 @@ protected String normalizeLineEndings(String string) {
     }
 
     public static class NormalizingStream extends InputStream {
-        private ByteArrayInputStream headerStream;
         private PushbackInputStream stream;
```
Comment (nvoxland) [inline liquibase-core/src/main/java/liquibase/change/AbstractSQLChange.java:285]: This probably doesn't have to be a PUshbackInputSTream anymore and can just be the InputStream itself?

File: liquibase-core/src/main/java/liquibase/change/core/CreateViewChange.java [hunk 2]
```diff
@@ -177,42 +177,47 @@ protected InputStream openSqlStream() throws IOException {
...
-            String selectQuery = this.selectQuery;
-            if ((stream == null) && (selectQuery == null)) {
-                selectQuery = "";
-            }
-
-            String encoding = GlobalConfiguration.OUTPUT_FILE_ENCODING.getCurrentValue();
-            if (selectQuery != null) {
+            if (this.path == null) {
+                String selectQuery = this.selectQuery;
+                String encoding = GlobalConfiguration.OUTPUT_FILE_ENCODING.getCurrentValue();
```
Comment (nvoxland) [inline liquibase-core/src/main/java/liquibase/change/core/CreateViewChange.java:202]: This should be FILE_ENCODING

**Review by nvoxland — CHANGES_REQUESTED** [review]

File: liquibase-core/src/main/java/liquibase/change/AbstractSQLChange.java (hunk 1 above)
Comment (MalloD12) [reply liquibase-core/src/main/java/liquibase/change/AbstractSQLChange.java]: Updated to InputStream.

File: liquibase-core/src/main/java/liquibase/change/core/CreateViewChange.java (hunk 2 above)
Comment (MalloD12) [reply liquibase-core/src/main/java/liquibase/change/core/CreateViewChange.java]: Updated to FILE_ENCODING

File: liquibase-core/src/main/java/liquibase/change/core/CreateProcedureChange.java [hunk 3]
```diff
@@ -240,39 +240,32 @@ public InputStream openSqlStream() throws IOException {
...
-                try {
-                    stream = new ByteArrayInputStream(procedureText.getBytes(encoding));
-                } catch (UnsupportedEncodingException e) {
-                    throw new AssertionError(encoding +
-                        " is not supported by the JVM, this should not happen according to the JavaDoc of " +
-                        "the Charset class"
-                    );
+            if (this.path == null) {
+                String procedureText = this.procedureText;
+                String encoding = GlobalConfiguration.OUTPUT_FILE_ENCODING.getCurrentValue();
```
Comment (nvoxland) [inline liquibase-core/src/main/java/liquibase/change/core/CreateProcedureChange.java:247]: This should be FILE_ENCODING

**Review by nvoxland — CHANGES_REQUESTED** [review]

File: liquibase-core/src/main/java/liquibase/change/core/CreateProcedureChange.java (hunk 3 above)
Comment (MalloD12) [reply liquibase-core/src/main/java/liquibase/change/core/CreateProcedureChange.java]: Done

File: liquibase-core/src/test/groovy/liquibase/change/core/CreateProcedureChangeTest.groovy [hunk 4]
```diff
@@ -90,11 +95,91 @@ public class CreateProcedureChangeTest extends StandardChangeTest {
...
+        CreateProcedureChange change2 = new CreateProcedureChange()
+        change2.setProcedureText(PROCEDURE_TEXT)
+        change2.setEncoding("UTF-8")
+        CheckSum procedureCheckSumWithEncoding = change2.generateCheckSum()
+
+        then:
+        procedureCheckSumWithoutEncoding == procedureCheckSumWithEncoding
+    }
+
+    def procedureTextUpdatedIsNotConsideredOnCheckSumGeneration() {
```
Comment (XDelphiGrl) [inline liquibase-core/src/test/groovy/liquibase/change/core/CreateProcedureChangeTest.groovy:173]: It might be better to name this test to indicate that whitespace changes to procedure check will not impact the checksum. Non-whitespace changes should (and do) change the checksum.

Comment (MalloD12) [reply liquibase-core/src/test/groovy/liquibase/change/core/CreateProcedureChangeTest.groovy:173]: Sure, I can do that.

Comment (MalloD12) [reply liquibase-core/src/test/groovy/liquibase/change/core/CreateProcedureChangeTest.groovy:173]: Updating this test name with `procedureTextUpdatedWithWhitespacesAddedShouldNotComputeANewCheckSum`. Maybe too long, but I think it's pretty self-explainable.

**Comment by XDelphiGrl** [comment]
Liquibase calculates a unique checksum for every changeset. This PR introduces a new version of the checksum that reduces the likelihood of false-positive changeset validation errors due to changes in `procedureText` and `selectQuery` attributes. The general rule of checksum calculation is that anything that _impacts_ the database is expected to throw a checksum validation error, whereas anything that does not impact the database should be excluded from the checksum calculation. Labels, contextFilter, dbms and whitespace are examples of elements of a changeset that are excluded from the checksum calculation. 

The purpose of this set of tests is to verify Liquibase correctly returns checksum validation errors due to database-impacting modifications of `createView` and `createProcedure` changesets. Conversely, these tests also verify Liquibase correctly **ignores** changeset modifications to `createView` and `createProcedures` that do not impact the database. 

**createView Checksum Validation Test Cases**
* Execute `calculate-checksum` for a `createView` changeset
* Edit the `createView` changeset as specified in the **What Changed?** column.
* Execute `calculate-checksum` for the altered `createView` changeset.

<html><body>


Changeset-Identifier | What Changed? | Orig Checksum | Expect
-- | -- | -- | --
DAT13003-changelog.xml::1-view::lbuser | whitespace in selectQuery | 9:5dd456b3f8e7b4d6f54f402633c47097 | No change in checksum
DAT13003-changelog.xml::1-view::lbuser | labels | 9:5dd456b3f8e7b4d6f54f402633c47097 | No change in checksum:check_mark:
DAT13003-changelog.xml::1-view::lbuser | context | 9:5dd456b3f8e7b4d6f54f402633c47097 | No change in checksum
DAT13003-changelog.xml::2-view::lbuser | contextFilter | 9:79692cbfbc3f497659b3d01ba48b3f66 | No change in checksum
DAT13003-changelog.xml::2-view::lbuser | dbms | 9:79692cbfbc3f497659b3d01ba48b3f66 | No change in checksum
DAT13003-changelog.xml::3-view::lbuser | relativeToChangeLogFile | 9:89d2421a4587a4f00294cbf466d439d4 | No change in checksum
DAT13003-changelog.xml::3-view::lbuser | encoding | 9:89d2421a4587a4f00294cbf466d439d4 | No change in checksum
DAT13003-changelog.xml::3-view::lbuser | path | 9:89d2421a4587a4f00294cbf466d439d4 | Checksum changes to 9:0424ba5c3aa704348a6de3c9c1ad5d8b
DAT13003-changelog.xml::3-view::lbuser | whitespace in SQL file | 9:89d2421a4587a4f00294cbf466d439d4 | No change in checksum.
DAT13003-changelog.xml::3-view::lbuser | non-whitespace in SQL file | 9:89d2421a4587a4f00294cbf466d439d4 | Checksum changes to 9:5d5cdd32fec1fb2028e8d2a973db21a7
DAT13003-changelog.xml::1-view::lbuser | non-whitespace in selectQuery | 9:5dd456b3f8e7b4d6f54f402633c47097 | Checksum changes to 9:aaa22cc084ad63834cc5103efc636085
DAT13003-changelog.xml::1-view::lbuser | viewName | 9:5dd456b3f8e7b4d6f54f402633c47097 | Checksum changes to 9:3283b84a0f6cf8f1ba135fb2ce5d47c1


</body>
</html>

**Procedure Checksum Validation Test Cases**
* Execute `calculate-checksum` for a `createProcedure` changeset
* Edit the `createProcedure` changeset as specified in the **What Changed?** column.
* Execute `calculate-checksum` for the altered `createProcedure` changeset.

<html><body>


Changeset-Identifier | What Changed? | Original Checksum | Expect
-- | -- | -- | --
DAT13003-changelog.xml::1-proc::lbuser | whitespace in SQL file | 9:7f81c91cc03bcdfdbaad066d1d239789 | No changes in checksum
DAT13003-changelog.xml::1-proc::lbuser | labels | 9:7f81c91cc03bcdfdbaad066d1d239789 | No changes in checksum
DAT13003-changelog.xml::1-proc::lbuser | context | 9:7f81c91cc03bcdfdbaad066d1d239789 | No changes in checksum
DAT13003-changelog.xml::1-proc::lbuser | path | 9:7f81c91cc03bcdfdbaad066d1d239789 | Checksum changes to 9:a0003da8b773326554c051f1117e1147
DAT13003-changelog.xml::1-proc::lbuser | path in rollback | 9:7f81c91cc03bcdfdbaad066d1d239789 | No changes in checksum
DAT13003-changelog.xml::1-proc::lbuser | relativeToChangeLogFile | 9:7f81c91cc03bcdfdbaad066d1d239789 | No changes in checksum
DAT13003-changelog.xml::2-proc::lbuser | contextFilter | 9:ca40bb3aaf03fbc100b967233ba5573c | No changes in checksum
DAT13003-changelog.xml::2-proc::lbuser | dbms | 9:ca40bb3aaf03fbc100b967233ba5573c | No changes in checksum
DAT13003-changelog.xml::2-proc::lbuser | fileEncoding | 9:ca40bb3aaf03fbc100b967233ba5573c | No changes in checksum
DAT13003-changelog.xml::2-proc::lbuser | add rollback change | 9:ca40bb3aaf03fbc100b967233ba5573c | No changes in checksum
DAT13003-changelog.xml::2-proc::lbuser | comments | 9:ca40bb3aaf03fbc100b967233ba5573c | No changes in checksum
DAT13003-changelog.xml::3-proc::lbuser | whitespace in procedureText | 9:a6f80ff21f3f0c73051f49f2ab06a8c8 | No checksum changes
DAT13003-changelog.xml::3-proc::lbuser | non-whitespace in procedureText | 9:a6f80ff21f3f0c73051f49f2ab06a8c8 | Checksum changes to 9:7203544264bbcef8dd68af8e145a49a5


</body>
</html>

**Comment by XDelphiGrl** [comment]
Calculating checksums for the `createProcedure` and `createView` changesets is one aspect of testing. The other is to ensure there is a smooth upgrade from the previous checksum version (8) to the one introduced by this PR (9). This set of tests verifies the checksum upgrade from version 8 to version 9 is successful.
* Checksum upgrade tests were executed by upgrading from the latest released Liquibase, v4.19.0.
  * It should be possible to upgrade from earlier versions of Liqubase but that is not a recommended or tested workflow.

**Upgrade from 8x to 9x Checksum Validation**

* Verify executing liquibase status gives a validation error for each of the deployed changesets. **PASS**
* Verify executing liquibase update-sql outputs SQL to null the checksums. **PASS**
* Verify executing liquibase update=sql ouputs SQL to update the DATABASECHANGELOG.MD5SUM column with v9 checksums for all changesets. **PASS**
* Verify executing liquibase update upgrades checksums to v9. **PASS**
* Veirfy the checksums for each changeset match the v9 checksum output by calculate-checksum in createView and createProcedure testing. **PASS**

**Review by XDelphiGrl — CHANGES_REQUESTED** [review]
I've left a comment for a test I'd like to see added to the CreateProcedureChangeTest class. I'd also like to ask you to add a similar CreateViewChangeTest class where we validate the same basic use cases (using `selectQuery` of course instead of `procedureText`). 

Other than that, everything looks great. I'll await your test changes and then this should be ready to merge to master! Thank you for the great work, @MalloD12 !

File: liquibase-core/src/test/groovy/liquibase/change/core/CreateProcedureChangeTest.groovy [hunk 5]
```diff
@@ -90,11 +95,91 @@ public class CreateProcedureChangeTest extends StandardChangeTest {
...
+        CreateProcedureChange change2 = new CreateProcedureChange()
+        change2.setProcedureText(PROCEDURE_TEXT)
+        change2.setEncoding("UTF-8")
+        CheckSum procedureCheckSumWithEncoding = change2.generateCheckSum()
+
+        then:
+        procedureCheckSumWithoutEncoding == procedureCheckSumWithEncoding
+    }
+
+    def procedureTextUpdatedWithWhitespacesAddedShouldNotComputeANewCheckSum() {
```
[the remark this answers is not in the document]
Comment (MalloD12) [reply liquibase-core/src/test/groovy/liquibase/change/core/CreateProcedureChangeTest.groovy:173]: Hi @XDelphiGrl,

Sure, I can work on these tests today. 

Just to double check, are saying to compute a checkSum value for a `CreateProcedure` change, then make a change on the procedure text, then re-compute checksum, and then validate this checksum is different to the first one generated? Is that the kind of scenario you are asking for, right?

Thanks a lot to you @XDelphiGrl for all your huge input on this case. I very much appreciate working with you and learning a lot from you!!

File: liquibase-core/src/test/java/liquibase/change/AbstractSQLChangeTest.java [hunk 6]
```diff
@@ -104,15 +104,15 @@ public void generateCheckSum_changesBasedOnParams() {
 
         ExampleAbstractSQLChange change = new ExampleAbstractSQLChange("SOME SQL");
         change.setSplitStatements(false);
-        assertNotEquals(baseCheckSum.toString(), change.generateCheckSum().toString());
+        assertEquals(baseCheckSum.toString(), change.generateCheckSum().toString());
```
[the remark this answers is not in the document]
Comment (MalloD12) [reply liquibase-core/src/test/java/liquibase/change/AbstractSQLChangeTest.java:107]: Sorry, I missed this question. If I'm not wrong this is because `splitStatements`, `endDelimiter` and `stripComments` are not considered for checksum generation. I don't know if this test makes really sense, but it was already there and I found out it was failing when trying to build the project after performing these changes.

[the remark this answers is not in the document]
Comment (XDelphiGrl) [reply liquibase-core/src/test/java/liquibase/change/AbstractSQLChangeTest.java:107]: No worries! That makes sense that `splitStatements`, `endDelimiter` and `stripComments` do not get included in the checksum calculation. Odd that they were passing prior to this PR, but your changes make sense.

File: liquibase-core/src/test/groovy/liquibase/change/core/CreateProcedureChangeTest.groovy (hunk 5 above)
[the remark this answers is not in the document]
Comment (XDelphiGrl) [reply liquibase-core/src/test/groovy/liquibase/change/core/CreateProcedureChangeTest.groovy:173]: @MalloD12, hi! 

Yes, what you are describing is exactly what I would like to see in a test. Thank you very much! It's been a lot of fun working on this PR with you for me, too! I'm glad you're on our team. :)

[the remark this answers is not in the document]
Comment (MalloD12) [reply liquibase-core/src/test/groovy/liquibase/change/core/CreateProcedureChangeTest.groovy]: @XDelphiGrl I just added the described test for `CreateProcedure` change, added most of the same checksum tests for `CreateView` change and made some minor refactoring on the tests name. Can you please look at them? Happy to make any other change or include any other test.

Thank you,
Daniel.

File: liquibase-core/src/test/groovy/liquibase/change/core/CreateProcedureChangeTest.groovy [hunk 7]
```diff
@@ -90,11 +91,106 @@ public class CreateProcedureChangeTest extends StandardChangeTest {
...
+        CheckSum procedureTextCheckSum = change.generateCheckSum()
+        CreateProcedureChange change2 = new CreateProcedureChange()
+        change2.setProcedureText(PROCEDURE_TEXT.concat("      \n"))
+        CheckSum procedureTextModifiedCheckSum = change2.generateCheckSum()
+
+        then:
+        assert procedureTextCheckSum == procedureTextModifiedCheckSum
+    }
+
+    def "checksum gets updated having a change on procedure text"() {
```
Comment (XDelphiGrl) [inline liquibase-core/src/test/groovy/liquibase/change/core/CreateProcedureChangeTest.groovy:182]: Thank you for adding this test, @MalloD12!

File: liquibase-core/src/test/groovy/liquibase/change/core/CreateProcedureChangeTest.groovy (hunk 5 above)
[the remark this answers is not in the document]
Comment (XDelphiGrl) [reply liquibase-core/src/test/groovy/liquibase/change/core/CreateProcedureChangeTest.groovy]: Thank you so much for adding the new tests, @MalloD12! This looks great.

**Review by XDelphiGrl — APPROVED** [review]
This PR introduces a new version of the checksum that reduces the likelihood of false-positive changeset validation errors due to whitespace changes in SQL associated with `createProcedure` and `createView` changesets.
* The `procedureText` element of `createProcedure` is the SQL included inline with the changeset OR in the referenced SQL file specified in the `path` attribute.
* The `selectQuery` element of `createView` is the SQL included inline with the changeset or in the SQL file referenced in the `path` attribute.
* Significant, non-whitespace changes to `procedureText` and `selectQuery` will throw a checksum validation error. This ensures that database-impacting changes to `createProcedure` and `createView` are not silently ignored.
* Test harness and functional test executions are passing. (Or they were previously... recent changes in this PR are to integration tests and will not impact test harness or functional test results).
* Manual testing complete (all details tracked in Liquibase internal ticket DAT-13003).
* No additional testing required.

**Notes**
* All checksums will be **recalculated** on the first update executed after upgrading to the release version of Liquibase including this PR. Any performance impact related to checksum recalculation will happen only once per changelog. If you have large changelogs, take this into account when you plan your Liquibase version upgrade.
* This PR cannot be released until the companion work to upgrade the checksum calculations for Pro stored logic changetypes is complete. Waiting to release the OSS checksum upgrades will  prevent users from needing a second checksum recalculation.

APPROVED

**Review by filipelautert — APPROVED** [review]

**Review by suryaaki2 — APPROVED** [review]

**Review by nvoxland — APPROVED** [review]
