### PR TITLE
fix: resource path resolution inside JAR files

### LINKED ISSUE #6784: Problem accessing <sqlFile> in a JAR via a relative path
### Search first

- [x] I searched and no similar issues were found

### Description

After upgrading from 4.15.0 to 4.31.1 we found exception, when execute our scripts.

We are often using relative pathes to our changes. So it works correctly until we updates to last release.

### Steps To Reproduce

I have a `changeset` with the file location specified using a relative path:
```
<changeSet author="vap" id="Create_package_usoi_trace_pkg" runAlways="true" runOnChange="true" runOrder="first" labels="oracle">
    <validCheckSum>ANY</validCheckSum>
    <comment>usoi_trace_pkg</comment>
    <sqlFile relativeToChangelogFile="true"
             path="../../oracle/package/usoi_trace_pkg.sql"
             endDelimiter="/"
             encoding="Cp1251"
             dbms="oracle"/>
</changeSet>
```
When building the application, the file `usoi_trace_pkg.sql` is located inside a nested JAR file:
`jar:file:C:/work/usoi5/usoi/core/build/libs/exploded/core.war/WEB-INF/lib/usoi-db-scripts-24.1-plain.jar!/com/asuproject/usoi/db/manage/scripts/oracle/package/usoi_trace_pkg.sql`

The changelog is located at:
`jar:file:C:/work/usoi5/usoi/core/build/libs/exploded/core.war/WEB-INF/lib/usoi-db-scripts-24.1-plain.jar!/com/asuproject/usoi/db/manage/scripts/liquibase/changelog.xml`

With this configuration, the method `ChangeSet.generateCheckSum` executes incorrectly and throws the following error:
`java.io.FileNotFoundException: JAR entry com/asuproject/usoi/db/manage/scripts/liquibase/scheme/../../oracle/package/usoi_trace_pkg.sql not found in C:\work\usoi5\usoi\core\build\libs\exploded\core.war\WEB-INF\lib\usoi-db-scripts-24.1-plain.jar`

### Expected/Desired Behavior

I noticed that the following call chain is executed:

`SQLFileChange.openSqlStream -> ResourceAccessor.openStream -> URIResource.resolveSibling -> URI.create() -> new AbstractResource()`

In the constructor of AbstractResource, the normalization of the URI should occur, transforming the following URI:

`jar:file:/C:/work/usoi5/usoi/core/build/libs/exploded/core.war/WEB-INF/lib/usoi-db-scripts-24.1-plain.jar!/com/asuproject/usoi/db/manage/scripts/liquibase/scheme/../../oracle/package/usoi_trace_pkg.sql
`

into this URI:

`jar:file:C:/work/usoi5/usoi/core/build/libs/exploded/core.war/WEB-INF/lib/usoi-db-scripts-24.1-plain.jar!/com/asuproject/usoi/db/manage/scripts/oracle/package/usoi_trace_pkg.sql`

However, when attempting to normalize such a path, no changes occur, and the path remains in its original format.

### Liquibase Version

4.31.1

### Database Vendor & Version

_No response_

### Liquibase Integration

_No response_

### Liquibase Extensions

_No response_

### OS and/or Infrastructure Type/Provider

Windows 10

### Additional Context

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

### PR DESCRIPTION
**Pull request by filipelautert**
## Impact

- [x] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
This PR fixes an issue with resource loading when resources are packaged
inside JAR files. The previous implementation had problems correctly resolving
paths within JARs due to incorrect URI handling of paths containing
exclamation marks (!).

The fix properly normalizes URIs in AbstractResource and improves path
resolution logic to ensure resources are correctly located, even when they're inside JAR files.

Fixes #6784

### CODE REVIEW

**Comment by filipelautert** [comment]
Hi @Gangamaniak - could you give this fix a try? You can download the zip file [here](https://github.com/liquibase/liquibase/actions/runs/14252103088/artifacts/2878659801) or obtain it using GPM [(gradle](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-gradle-registry#using-a-published-package) or [maven](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry) ):

```
<dependency>
  <groupId>org.liquibase</groupId>
  <artifactId>liquibase-core</artifactId>
  <version>f10351368534f34f37dd43a2bccdf4a911dd7bc6-SNAPSHOT</version>
</dependency>
```

**Comment by Gangamaniak** [comment]
Hi @filipelautert 
I tried this version and my application starts up correctly. No errors are observed during launch.

**Comment by filipelautert** [comment]
> Hi @filipelautert I tried this version and my application starts up correctly. No errors are observed during launch.

Thanks for testing!

File: liquibase-standard/src/main/java/liquibase/resource/AbstractResource.java [hunk 1]
```diff
@@ -13,16 +16,51 @@ public abstract class AbstractResource implements Resource {
...
         if (uri != null) {
-            this.uri = uri.normalize();
+            this.uri = handleUriSyntax(uri);
         } else {
             this.uri = null;
         }
+
+        String pathL = path
+                .replace("\\", "/")
+                .replaceFirst("^classpath\\*?:", "");
```
Comment (MalloD12) [inline liquibase-standard/src/main/java/liquibase/resource/AbstractResource.java:27]: Question: Before doing this replacement here, shouldn't we consider how's set `PRESERVE_CLASSPATH_PREFIX_IN_NORMALIZED_PATHS`?

Comment (filipelautert) [reply liquibase-standard/src/main/java/liquibase/resource/AbstractResource.java:27]: Good question.. this change was already in the code so i considered it to be working before.

File: liquibase-standard/src/main/java/liquibase/resource/AbstractResource.java [hunk 2]
```diff
@@ -13,16 +16,51 @@ public abstract class AbstractResource implements Resource {
...
+        // URI doesn't work as expected. So we need some manual handling
+        if (uri.toString().contains(("!"))) {
+            String[] uriSplit = uri.toString().split(("!"));
+            try {
+                return new URI(uriSplit[0] + "!" + new URI(uriSplit[1]).normalize());
+            } catch (URISyntaxException e) {
+                return uri.normalize();
+            }
+        }
+        return uri.normalize();
```
Comment (StevenMassaro) [inline liquibase-standard/src/main/java/liquibase/resource/AbstractResource.java:63]: Is there a chance that a single URI could have multiple exclamation points in it? If so, this would not work.

File: liquibase-standard/src/main/java/liquibase/resource/AbstractResource.java [hunk 3]
```diff
@@ -13,16 +16,51 @@ public abstract class AbstractResource implements Resource {
...
-                .replaceFirst("^/", "");
-
         if (uri != null) {
-            this.uri = uri.normalize();
+            this.uri = handleUriSyntax(uri);
         } else {
             this.uri = null;
         }
+
+        String pathL = path
```
Comment (StevenMassaro) [inline liquibase-standard/src/main/java/liquibase/resource/AbstractResource.java:25]: Can you come up with a more descriptive variable name than `pathL`? It would be easy to accidentally type `path` and not notice.

File: liquibase-standard/src/main/java/liquibase/resource/AbstractResource.java (hunk 2 above)
Comment (tati-qalified) [reply liquibase-standard/src/main/java/liquibase/resource/AbstractResource.java:63]: in that case, this could be fixed by looping while uri.toString().contains(("!"))

**Review by rberezen — APPROVED** [review]

**Review by tati-qalified — APPROVED** [review]
