### PR TITLE
Fix foreignKeyConstraintExists precondition when constraint already exists in the DB

### LINKED ISSUE #6648: Bug in version 4.30.0 and 4.31.0 : foreignKeyConstraintExists precondition does not work
### Search first

- [x] I searched and no similar issues were found

### Description

We have tested an existing changelog with version 4.30.0. A changeset which uses a foreignKeyConstraintExists precondition is executed even if the foreign key actually does exist in the database, which causes it to fail.

The database is an oracle 19c database.

### Steps To Reproduce

Create a schema with two tables, and one foreign key:

```
create user myschema no authentication;
grant unlimited tablespace to myschema;
create table myschema.my_other_table (my_fk_column number);
alter table MYSCHEMA.MY_OTHER_TABLE
  add constraint MY_OTHER_TABLE_PK primary key (MY_FK_COLUMN);

create table myschema.my_table (my_fk_column number);
alter table MYSCHEMA.MY_TABLE
  add constraint MY_FOREIGN_KEY foreign key (MY_FK_COLUMN)
  references MYSCHEMA.my_other_table (MY_FK_COLUMN);

```

Then run the following changeset with liquibase 4.30.0. This fails. It does not fail with previous versions of liquibase.

```
- changeSet:
    id: addForeignKeyConstraint  MYSCHEMA, foreignKeyName MY_FOREIGN_KEY, foreignKeyTableName MY_TABLE
    author: ${MODULE_NAME}
    preConditions:
      - onFail: MARK_RAN
      - not:
        - foreignKeyConstraintExists:
            schemaName: MYSCHEMA
            foreignKeyName: MY_FOREIGN_KEY
            foreignKeyTableName: MY_TABLE
    changes:
    - addForeignKeyConstraint:
        baseColumnNames: MY_FK_COLUMN
        baseTableName: MY_TABLE
        baseTableSchemaName: MYSCHEMA
        constraintName: MY_FOREIGN_KEY
        deferrable: false
        initiallyDeferred: false
        onDelete: RESTRICT
        onUpdate: RESTRICT
        referencedColumnNames: MY_FK_COLUMN
        referencedTableCatalogName: MYSCHEMA
        referencedTableName: MY_OTHER_TABLE
        validate: true
```

### Expected/Desired Behavior

The precondition check must discover the existing foreign key, so that the changeset is marked as ran instead of failing

### Liquibase Version

4.30.0

### Database Vendor & Version

Oracle 19c

### Liquibase Integration

_No response_

### Liquibase Extensions

_No response_

### OS and/or Infrastructure Type/Provider

_No response_

### Additional Context

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

### PR DESCRIPTION
**Pull request by MalloD12**
- Fix for ForeignKetExists preconditions to use default catalog if DB supports schema.
- Tests added for Oracle, Mssql, Postgres and MySQL.

## Impact

- [x] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 

## Description
Fixes #6648

### CODE REVIEW

File: liquibase-standard/src/main/java/liquibase/precondition/core/ForeignKeyExistsPrecondition.java [hunk 1]
```diff
@@ -50,8 +50,12 @@ public void check(Database database, DatabaseChangeLog changeLog, ChangeSet chan
                 example.getForeignKeyTable().setName(getForeignKeyTableName());
             }
             String catalogName = getCatalogName() != null ? getCatalogName() : database.getDefaultCatalogName();
+            String localCatalogName = getCatalogName();
+            if (database.supports(Schema.class) && localCatalogName == null) {
```
Comment (filipelautert) [inline liquibase-standard/src/main/java/liquibase/precondition/core/ForeignKeyExistsPrecondition.java:54]: Should not be `database.supports(Catalog.class)` as we are dealing with `Catalog`  ?

**Review by filipelautert — CHANGES_REQUESTED** [review]

File: liquibase-standard/src/main/java/liquibase/precondition/core/ForeignKeyExistsPrecondition.java (hunk 1 above)
Comment (wwillard7800) [reply liquibase-standard/src/main/java/liquibase/precondition/core/ForeignKeyExistsPrecondition.java:54]: This was my idea, and while it solves this issue, I'm not sure if it is correct.  Oracle is backwards (to me), which made me think it needed to be `Schema` instead of `Catalog`.

Comment (filipelautert) [reply liquibase-standard/src/main/java/liquibase/precondition/core/ForeignKeyExistsPrecondition.java:54]: Should this be Oracle-specific?

Comment (wwillard7800) [reply liquibase-standard/src/main/java/liquibase/precondition/core/ForeignKeyExistsPrecondition.java:54]: That would be a safer change, yes.

File: liquibase-standard/src/main/java/liquibase/precondition/core/ForeignKeyExistsPrecondition.java [hunk 2]
```diff
@@ -49,7 +51,10 @@ public void check(Database database, DatabaseChangeLog changeLog, ChangeSet chan
             if (StringUtils.trimToNull(getForeignKeyTableName()) != null) {
                 example.getForeignKeyTable().setName(getForeignKeyTableName());
             }
-            String catalogName = getCatalogName() != null ? getCatalogName() : database.getDefaultCatalogName();
+            String catalogName = getCatalogName();
+            if(!(database instanceof OracleDatabase) && getCatalogName() == null) {
```
Comment (filipelautert) [inline liquibase-standard/src/main/java/liquibase/precondition/core/ForeignKeyExistsPrecondition.java:55]: Nice!

**Review by rberezen — APPROVED** [review]

**Review by tati-qalified — APPROVED** [review]
