### PR TITLE
not to use class field for thread safe.

### LINKED ISSUE #4376: Liquibase commands are not thread safe even with ThreadLocalScopeManager
### Search first

- [X] I searched and no similar issues were found

### Description

We are running Liquibase commands using Java APIs on multiple databases concurrently with `ThreadLocalScopeManager`. 
We are noticing that the Liquibase commands are not thread safe. The connection object is being shared across threads leading to connection closed exceptions. 

**Code Snippet**

```
Scope.setScopeManager(new ThreadLocalScopeManager());

ExecutorService executor = Executors.newFixedThreadPool(8);

for (int i=0; i<10; i++) {
            String dbName = "DB_" + i;
            executor.submit( () -> {
                try(MemoryDatabase db = MemoryDatabase.create(dbName); Connection con = db.getConnection()) {
                    final Liquibase liquibase = new Liquibase(
                            "com/example/changelog.xml",
                            new ClassLoaderResourceAccessor(),
                            new JdbcConnection(con));
                    liquibase.tag("test_started");
                    liquibase.update(new Contexts(), new LabelExpression());
                    liquibase.tag("test_complete");
                } catch (LiquibaseException e) {
                    throw new IllegalStateException(e.getMessage(), e);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
          });
  }
```

**Exception StackTrace**

```
Caused by: liquibase.exception.CommandExecutionException: liquibase.exception.LockException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE PUBLIC.DATABASECHANGELOGLOCK (ID INT NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP, LOCKEDBY VARCHAR(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID)): The object is already closed [90007-193]
	at liquibase.command.CommandScope.execute(CommandScope.java:235)
	at liquibase.Liquibase.lambda$update$0(Liquibase.java:237)
	at liquibase.Scope.lambda$child$0(Scope.java:194)
	at liquibase.Scope.child(Scope.java:203)
	at liquibase.Scope.child(Scope.java:193)
	at liquibase.Scope.child(Scope.java:172)
	at liquibase.Liquibase.runInScope(Liquibase.java:1605)
	at liquibase.Liquibase.update(Liquibase.java:229)
	at liquibase.Liquibase.update(Liquibase.java:213)
	at com.example.persistence.dbmigration.ThreadLocalScopeManagerTest.maintainDatabase(ThreadLocalScopeManagerTest.java:89)
	... 6 more
Caused by: liquibase.exception.LockException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE PUBLIC.DATABASECHANGELOGLOCK (ID INT NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP, LOCKEDBY VARCHAR(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID)): The object is already closed [90007-193]
	at liquibase.lockservice.StandardLockService.acquireLock(StandardLockService.java:337)
	at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:254)
	at liquibase.command.core.helpers.LockServiceCommandStep.run(LockServiceCommandStep.java:37)
	at liquibase.command.CommandScope.execute(CommandScope.java:212)
	... 15 more
Caused by: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE PUBLIC.DATABASECHANGELOGLOCK (ID INT NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP, LOCKEDBY VARCHAR(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID)): The object is already closed [90007-193]
	at liquibase.executor.jvm.ChangelogJdbcMdcListener.execute(ChangelogJdbcMdcListener.java:39)
	at liquibase.lockservice.StandardLockService.init(StandardLockService.java:117)
	at liquibase.lockservice.StandardLockService.acquireLock(StandardLockService.java:293)
	... 18 more
Caused by: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE PUBLIC.DATABASECHANGELOGLOCK (ID INT NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP, LOCKEDBY VARCHAR(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID)): The object is already closed [90007-193]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:89)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:160)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:125)
	at liquibase.lockservice.StandardLockService.lambda$init$0(StandardLockService.java:117)
	at liquibase.executor.jvm.ChangelogJdbcMdcListener.lambda$execute$0(ChangelogJdbcMdcListener.java:33)
	at liquibase.Scope.lambda$child$0(Scope.java:194)
	at liquibase.Scope.child(Scope.java:203)
	at liquibase.Scope.child(Scope.java:193)
	at liquibase.Scope.child(Scope.java:172)
	at liquibase.executor.jvm.ChangelogJdbcMdcListener.execute(ChangelogJdbcMdcListener.java:32)
	... 20 more
Caused by: org.h2.jdbc.JdbcSQLException: The object is already closed [90007-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1480)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1458)
	at org.h2.jdbc.JdbcConnection.createStatement(JdbcConnection.java:202)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:74)
	... 29 more
```

On basic investigation it looks like an issue with `LockServiceCommandStep`  where `database` is a class member. 

And looks like multiple threads are using the same `LockServiceCommandStep` object even though we have set `ThreadLocalScopeManager`. 

This seems to be because the  command objects are being created in the `rootScope` being set in the constructor of `ThreadLocalScopeManager`

```
public ThreadLocalScopeManager() {
    this.rootScope = Scope.getCurrentScope();
}
```

https://github.com/liquibase/liquibase/blob/master/liquibase-standard/src/main/java/liquibase/Scope.java#L327
```
public synchronized <T extends SingletonObject> T getSingleton(Class<T> type) {
    if (getParent() != null) {
        return getParent().getSingleton(type);
 }
```

This looks to be incorrect since the expectation when using `ThreadLocalScopeManager` is that liquibase command objects are scoped to a specific thread and not reused across threads.

### Steps To Reproduce

This issue can be reproduced by running the following test in liquibase project https://github.com/liquibase/liquibase/blob/master/liquibase-standard/src/test/groovy/liquibase/ThreadLocalScopeManagerTest.groovy

This issue is consistently reproducible by running the above test with `@RepeatedTest(10)`. Look for exceptions in the logs.

Note: Above test is actually Ignored in the liquibase codebase (maybe due to this issue?)

### Expected/Desired Behavior

We expect Liquibase commands to be thread safe when run under a heavy thread load. 

### Liquibase Version

4.22.0

### Database Vendor & Version

PostgreSQL 12.2

### Liquibase Integration

Java API

### Liquibase Extensions

_No response_

### OS and/or Infrastructure Type/Provider

_No response_

### Additional Context

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

### PR DESCRIPTION
**Pull request by Wenkee**
## Impact

- [x] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

Liquibase commands are not thread safe even with ThreadLocalScopeManager . 

Exception StackTrace

```
Caused by: liquibase.exception.CommandExecutionException: liquibase.exception.LockException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE PUBLIC.DATABASECHANGELOGLOCK (ID INT NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP, LOCKEDBY VARCHAR(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID)): The object is already closed [90007-193]
	at liquibase.command.CommandScope.execute(CommandScope.java:235)
	at liquibase.Liquibase.lambda$update$0(Liquibase.java:237)
	at liquibase.Scope.lambda$child$0(Scope.java:194)
	at liquibase.Scope.child(Scope.java:203)
	at liquibase.Scope.child(Scope.java:193)
	at liquibase.Scope.child(Scope.java:172)
	at liquibase.Liquibase.runInScope(Liquibase.java:1605)
	at liquibase.Liquibase.update(Liquibase.java:229)
	at liquibase.Liquibase.update(Liquibase.java:213)
	at com.example.persistence.dbmigration.ThreadLocalScopeManagerTest.maintainDatabase(ThreadLocalScopeManagerTest.java:89)
	... 6 more
Caused by: liquibase.exception.LockException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE PUBLIC.DATABASECHANGELOGLOCK (ID INT NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP, LOCKEDBY VARCHAR(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID)): The object is already closed [90007-193]
	at liquibase.lockservice.StandardLockService.acquireLock(StandardLockService.java:337)
	at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:254)
	at liquibase.command.core.helpers.LockServiceCommandStep.run(LockServiceCommandStep.java:37)
	at liquibase.command.CommandScope.execute(CommandScope.java:212)
	... 15 more
Caused by: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE PUBLIC.DATABASECHANGELOGLOCK (ID INT NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP, LOCKEDBY VARCHAR(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID)): The object is already closed [90007-193]
	at liquibase.executor.jvm.ChangelogJdbcMdcListener.execute(ChangelogJdbcMdcListener.java:39)
	at liquibase.lockservice.StandardLockService.init(StandardLockService.java:117)
	at liquibase.lockservice.StandardLockService.acquireLock(StandardLockService.java:293)
	... 18 more
Caused by: liquibase.exception.DatabaseException: Error executing SQL CREATE TABLE PUBLIC.DATABASECHANGELOGLOCK (ID INT NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP, LOCKEDBY VARCHAR(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID)): The object is already closed [90007-193]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:89)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:160)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:125)
	at liquibase.lockservice.StandardLockService.lambda$init$0(StandardLockService.java:117)
	at liquibase.executor.jvm.ChangelogJdbcMdcListener.lambda$execute$0(ChangelogJdbcMdcListener.java:33)
	at liquibase.Scope.lambda$child$0(Scope.java:194)
	at liquibase.Scope.child(Scope.java:203)
	at liquibase.Scope.child(Scope.java:193)
	at liquibase.Scope.child(Scope.java:172)
	at liquibase.executor.jvm.ChangelogJdbcMdcListener.execute(ChangelogJdbcMdcListener.java:32)
	... 20 more
Caused by: org.h2.jdbc.JdbcSQLException: The object is already closed [90007-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1480)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1458)
	at org.h2.jdbc.JdbcConnection.createStatement(JdbcConnection.java:202)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:74)
	... 29 more
```

Fix #4376

### CODE REVIEW

**Review by suryaaki2 — APPROVED** [review]

File: liquibase-standard/src/main/java/liquibase/command/core/helpers/LockServiceCommandStep.java [hunk 1]
```diff
@@ -45,7 +45,9 @@ public String[][] defineCommandNames() {
     @Override
     public void cleanUp(CommandResultsBuilder resultsBuilder) {
         try {
-            LockServiceFactory.getInstance().getLockService(database).releaseLock();
```
Comment (filipelautert) [inline liquibase-standard/src/main/java/liquibase/command/core/helpers/LockServiceCommandStep.java:48]: As you removed the usage of the class field database, could you also move declaration to `run ` method and remove it from class level? 
Thanks

**Review by filipelautert — APPROVED** [review]
