### PR TITLE
Fixed NullPointerException in SecureLogFilter.isLoggable

### LINKED ISSUE #1858: NullPointerException inside SecureLogFilter.isLoggable
I am running from OSX homebrew and connecting to a Mysql database.  A temporary workaround is to run without --loglevel=info

Caused by: java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "filteredMessage" is null
	at liquibase.integration.commandline.Main$SecureLogFilter.isLoggable(Main.java:2159)
	at java.logging/java.util.logging.Handler.isLoggable(Handler.java:346)
	at java.logging/java.util.logging.StreamHandler.isLoggable(StreamHandler.java:237)
	at java.logging/java.util.logging.StreamHandler.publish(StreamHandler.java:194)
	at java.logging/java.util.logging.ConsoleHandler.publish(ConsoleHandler.java:95)
	at java.logging/java.util.logging.Logger.log(Logger.java:979)
	at java.logging/java.util.logging.Logger.doLog(Logger.java:1006)
	at java.logging/java.util.logging.Logger.logp(Logger.java:1283)
	at liquibase.logging.core.JavaLogger.log(JavaLogger.java:23)
	at liquibase.logging.core.CompositeLogger.log(CompositeLogger.java:29)
	at liquibase.logging.core.CompositeLogger.log(CompositeLogger.java:29)
	at liquibase.logging.core.AbstractLogger.info(AbstractLogger.java:50)
	at liquibase.logging.core.AbstractLogger.info(AbstractLogger.java:45)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:638)

### PR DESCRIPTION
**Pull request by nikosmoum**
## Environment

**Liquibase Version**: 4.8.0

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: none

**Database Vendor & Version**: I don't think it matters, but I tested with Postgres 12

**Operating System Type & Version**: all (I tested on Fedora35)

## Pull Request Type

- [x] Bug fix (non-breaking change which fixes an issue.)
- [ ] Enhancement/New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Fixes #1858

## Steps To Reproduce

List the steps to reproduce the behavior.
- Create a changelog.xml that uses a custom task (that implements `liquibase.change.custom.CustomTaskChange`).
- In the custom task, override the getConfirmationMessage method to return null:
```
    @Override
    public String getConfirmationMessage() {
        return null;
    }
```
- Run the 'update' command from the CLI, using either the `liquibase.integration.commandline.Main` or `liquibase.integration.commandline.LiquibaseCommandLine`, and setting the `--log-level=` argument (it's value doesn't matter, could be info/debug/whatever)

## Actual Behavior
The update fails. Here is the last part of the stacktrace:
```
Caused by: java.lang.NullPointerException
	at liquibase.integration.commandline.LiquibaseCommandLine$SecureLogFilter.isLoggable(LiquibaseCommandLine.java:1055)
	at java.logging/java.util.logging.Handler.isLoggable(Handler.java:346)
	at java.logging/java.util.logging.StreamHandler.isLoggable(StreamHandler.java:237)
	at java.logging/java.util.logging.StreamHandler.publish(StreamHandler.java:194)
	at java.logging/java.util.logging.ConsoleHandler.publish(ConsoleHandler.java:95)
	at java.logging/java.util.logging.Logger.log(Logger.java:979)
	at java.logging/java.util.logging.Logger.doLog(Logger.java:1006)
	at java.logging/java.util.logging.Logger.logp(Logger.java:1283)
	at liquibase.logging.core.JavaLogger.log(JavaLogger.java:30)
	at liquibase.logging.core.CompositeLogger.log(CompositeLogger.java:33)
	at liquibase.logging.core.CompositeLogger.log(CompositeLogger.java:33)
	at liquibase.logging.core.AbstractLogger.info(AbstractLogger.java:50)
	at liquibase.logging.core.AbstractLogger.info(AbstractLogger.java:45)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:662)
	... 62 more
```

## Expected/Desired Behavior
The update should succeed.

## Fast Track PR Acceptance Checklist:

- [x] Build is successful and all new and existing tests pass
- [x] Added [Unit Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)
- [ ] Added [Integration Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)
- [ ] Added [Test Harness Test(s)](https://github.com/liquibase/liquibase-test-harness/pulls)
- [ ] Documentation Updated

## Need Help?
Come chat with us on our [discord channel](https://discord.com/channels/700506481111597066/700506481572839505)

### CODE REVIEW

**Review by nvoxland — APPROVED** [review]

**Comment by nvoxland** [comment]
The SafeToBuild label is something we have to add based on reviewing the code. It's a temporary solution as we're fixing up the build logic to be more secure

**Comment by XDelphiGrl** [comment]
@nvoxland, this build did not run, despite having the `SafeToBuild` label. Can you take a look please?

**Comment by nvoxland** [comment]
#2777 removes this class completely, so if that PR gets merged first this can be closed as "unneeded"

File: liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy [hunk 1]
```diff
@@ -3,10 +3,12 @@ package liquibase.integration.commandline
 
 import liquibase.command.CommandBuilder
 import liquibase.configuration.ConfigurationDefinition
-import picocli.CommandLine
+import liquibase.logging.LogMessageFilter
```
Comment (XDelphiGrl) [inline liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy:6]: @nvoxland, can you please confirm that we want to swap out piccoli.CommandLine in favor of using liquibase.logging.LogMessageFilter? I ask because there are plans to deprecate the LogMessageFilter class.

CC @nikosmoum

Comment (nvoxland) [reply liquibase-cli/src/test/groovy/liquibase/integration/commandline/LiquibaseCommandLineTest.groovy:6]: That is the right class to be importing, and also part of why this PR won't be needed if/when #2777 goes through. I just hadn't closed this one yet since whether we want to do this or not will depend on what happens with 2777

**Review by XDelphiGrl — APPROVED** [review]
* Fix is focused on addressing a Null Pointer.
* New integration and unit tests added.
* No further testing required.

[Passing Test Harness Execution](https://github.com/liquibase/liquibase-test-harness/actions/runs/2294161207)
[Passing Functional Tests](https://github.com/liquibase/liquibase-pro-tests/actions/runs/2203730636)

APPROVED
