### PR TITLE
fix(mysql/mariadb): respect columnDataType in renameColumn for modern versions

### LINKED ISSUE #7339: MariaDB renameColumn regression bug: columnDataType is ignored
### Search first

- [x] I searched and no similar issues were found

### Description

I found that using MariaDB 10.11 and liquibase-maven-plugin version 5.0.0, the renameColumn change type stops working as expected.

I drilled down to this bugfix: #6876 which introduces the `RENAME COLUMN` syntax for MySQL/MariaDb.
However, this bugfix introduced regression when changing the column's datatype together with its name.

### Steps To Reproduce

Initial ChangeSet:
```
<createTable tableName="PERSON">
      ...
      <column name="NAME" type="VARCHAR(32)">
        <constraints nullable="false"/>
      </column>
      ...
 </createTable>
```

Followup ChangeSet:
```
<renameColumn tableName="PERSON" oldColumnName="NAME"
      newColumnName="NEW_NAME" columnDataType="VARCHAR(64)"/>
```

This effectively ignores the columnDataType set on the renameColumn and in my opinion is an unwanted change in existing behavior.

The generated SQL changes from:

`ALTER TABLE PERSON CHANGE NAME NEW_NAME VARCHAR(64);`
to
`ALTER TABLE PERSON RENAME COLUMN NAME TO NEW_NAME;`

### Expected/Desired Behavior

One could argue that the renameColumn change type is not intended to change the columnDataType in one go, but it causes regression as the columnDataType field is just ignored instead of applied. The desired behavior is in my opinion, that if the columnDataType field is supplied to the changeSet, it is taken into account in the alter table statement and not just forgotten.

### Liquibase Version

5.0.0

### Database Vendor & Version

MariaDB 10.11

### Liquibase Integration

Maven plugin

### Liquibase Extensions

mariadb-java-client

### OS and/or Infrastructure Type/Provider

_No response_

### Additional Context

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

### PR DESCRIPTION
**Pull request by filipelautert**
## Summary
- Uses `CHANGE` syntax when `columnDataType` is provided on MariaDB 10.5+ and MySQL 8.0+
- Uses `RENAME COLUMN` syntax when only renaming (no type change) is needed
- Preserves backward compatibility with older database versions

## Problem
In Liquibase 5.0.0, the `renameColumn` change type for MariaDB/MySQL ignores the `columnDataType` parameter when the database supports `RENAME COLUMN` syntax. This causes the type change to be silently discarded.

**Example:**
```xml
<renameColumn tableName="PERSON" oldColumnName="NAME"
  newColumnName="NEW_NAME" columnDataType="VARCHAR(64)"/>
```

**Expected:** `ALTER TABLE PERSON CHANGE NAME NEW_NAME VARCHAR(64);`
**Actual:** `ALTER TABLE PERSON RENAME COLUMN NAME TO NEW_NAME;` (type change ignored!)

## Solution
Modified `RenameColumnGenerator.generateMysqlStatement()` to check if `columnDataType` is provided:
- If `columnDataType` is null/empty AND `RENAME COLUMN` is supported → use `RENAME COLUMN` syntax
- If `columnDataType` is provided → use `CHANGE` syntax (regardless of version)

## Test plan
- [x] Added 37 Spock tests covering all MySQL/MariaDB version combinations
- [x] Verified existing RenameColumn tests still pass (41 total tests)
- [ ] Manual testing with MariaDB 10.11 to verify type change works

Fixes #7339

### CODE REVIEW

File: liquibase-standard/src/main/java/liquibase/sqlgenerator/core/RenameColumnGenerator.java [hunk 1]
```diff
@@ -83,10 +83,35 @@ public Sql[] generateSql(RenameColumnStatement statement, Database database, Sql
...
+                    + " RENAME COLUMN " + database.escapeColumnName(statement.getCatalogName(), statement.getSchemaName(), statement.getTableName(), statement.getOldColumnName())
+                    + " TO " + database.escapeColumnName(statement.getCatalogName(), statement.getSchemaName(), statement.getTableName(), statement.getNewColumnName());
+        }
+
+        // Use CHANGE syntax when columnDataType is specified (for type changes) or when RENAME COLUMN is not supported
+        return "ALTER TABLE " + database.escapeTableName(statement.getCatalogName(), statement.getSchemaName(), statement.getTableName())
+                + " CHANGE " + database.escapeColumnName(statement.getCatalogName(), statement.getSchemaName(), statement.getTableName(), statement.getOldColumnName())
+                + " " + database.escapeColumnName(statement.getCatalogName(), statement.getSchemaName(), statement.getTableName(), statement.getNewColumnName())
+                + " " + DataTypeFactory.getInstance().fromDescription(columnDataType, database).toDatabaseDataType(database);
```
Comment (MalloD12) [inline liquibase-standard/src/main/java/liquibase/sqlgenerator/core/RenameColumnGenerator.java:114]: This is a question not from this current PR changes, but I was just looking at the `isRenameKeywordSupported()` function, and I was wondering whether the `else` block should not be checking if database is a `mysql` one to avoid this getting applied to any other DB that a major version greater or equals than `8`.

Comment (filipelautert) [reply liquibase-standard/src/main/java/liquibase/sqlgenerator/core/RenameColumnGenerator.java:114]: Good question! The concern isn't actually an issue here because the method signature isRenameKeywordSupported(MySQLDatabase database) already constrains the input to only MySQL-family databases.

  The else block can only be reached by MySQLDatabase instances (since MariaDBDatabase is caught by the if). No other database type can get here - Java's type system guarantees it.

  So the version check >= 8 is safe and will only ever apply to actual MySQL databases. No additional instanceof check needed! 👍

Comment (MalloD12) [reply liquibase-standard/src/main/java/liquibase/sqlgenerator/core/RenameColumnGenerator.java:114]: Good point, didn't realize the database parameter was already a MySQLDtabase instance. 

Thanks!
